import type { UILanguage } from '../types';

type Translations = Record<string, Partial<Record<UILanguage, string>>>;

const T: Translations = {
  // ===== NAVBAR =====
  'nav.brand': { en: 'Cinema AI Studio', he: 'Cinema AI Studio', ar: 'Cinema AI Studio', fr: 'Cinema AI Studio', zh: 'Cinema AI Studio', pt: 'Cinema AI Studio', es: 'Cinema AI Studio', de: 'Cinema AI Studio', it: 'Cinema AI Studio', ru: 'Cinema AI Studio', ko: 'Cinema AI Studio', ja: 'Cinema AI Studio' },
  'nav.howItWorks': { en: 'How It Works', he: 'איך זה עובד', ar: 'كيف يعمل', fr: 'Comment ça marche', zh: '工作原理', pt: 'Como funciona', es: 'Cómo funciona', de: 'So funktioniert es', it: 'Come funziona', ru: 'Как это работает', ko: '작동 방식', ja: '使い方' },
  'nav.useCases': { en: 'Use Cases', he: 'שימושים', ar: 'حالات الاستخدام', fr: 'Cas d\'utilisation', zh: '使用场景', pt: 'Casos de uso', es: 'Casos de uso', de: 'Anwendungsfälle', it: 'Casi d\'uso', ru: 'Варианты использования', ko: '활용 사례', ja: '活用例' },
  'nav.pricing': { en: 'Pricing', he: 'מחירים', ar: 'الأسعار', fr: 'Tarifs', zh: '定价', pt: 'Preços', es: 'Precios', de: 'Preise', it: 'Prezzi', ru: 'Цены', ko: '요금', ja: '料金' },
  'nav.discover': { en: 'Discover', he: 'גלה', ar: 'اكتشف', fr: 'Découvrir', zh: '发现', pt: 'Descobrir', es: 'Descubrir', de: 'Entdecken', it: 'Scopri', ru: 'Обзор', ko: '탐색', ja: '発見' },
  'nav.tryFree': { en: 'Try Free', he: 'נסה בחינם', ar: 'جرب مجاناً', fr: 'Essai gratuit', zh: '免费试用', pt: 'Teste grátis', es: 'Prueba gratis', de: 'Kostenlos testen', it: 'Prova gratis', ru: 'Попробовать', ko: '무료 체험', ja: '無料で試す' },

  // ===== HERO =====
  'hero.badge': { en: 'Powered by Google Veo 3.1', he: 'מופעל על ידי Google Veo 3.1', ar: 'مدعوم بتقنية Google Veo 3.1', fr: 'Propulsé par Google Veo 3.1', zh: '由 Google Veo 3.1 驱动', pt: 'Powered by Google Veo 3.1', es: 'Impulsado por Google Veo 3.1', de: 'Powered by Google Veo 3.1', it: 'Powered by Google Veo 3.1', ru: 'На базе Google Veo 3.1', ko: 'Google Veo 3.1 기반', ja: 'Google Veo 3.1 搭載' },
  'hero.title': { en: 'Your Story Deserves\nto Be Seen', he: 'הסיפור שלך\nראוי להיראות', ar: 'قصتك تستحق\nأن تُرى', fr: 'Votre histoire mérite\nd\'être vue', zh: '你的故事\n值得被看见', pt: 'Sua história merece\nser vista', es: 'Tu historia merece\nser vista', de: 'Deine Geschichte\nverdient es, gesehen zu werden', it: 'La tua storia merita\ndi essere vista', ru: 'Ваша история\nзаслуживает быть увиденной', ko: '당신의 이야기는\n보여질 자격이 있습니다', ja: 'あなたの物語は\n見られるべきです' },
  'hero.sub': { en: 'Turn any text into a cinematic film. Paste a story, choose a style, and watch AI bring it to life.', he: 'הפוך כל טקסט לסרט קולנועי. הדבק סיפור, בחר סגנון, וצפה ב-AI מביא אותו לחיים.', ar: 'حوّل أي نص إلى فيلم سينمائي. الصق قصة، اختر أسلوباً، وشاهد الذكاء الاصطناعي يبث فيها الحياة.', fr: 'Transformez n\'importe quel texte en film cinématographique. Collez une histoire, choisissez un style, et regardez l\'IA lui donner vie.', zh: '将任何文本转化为电影。粘贴故事，选择风格，观看AI将其变为现实。', pt: 'Transforme qualquer texto em um filme cinematográfico. Cole uma história, escolha um estilo e veja a IA dar vida a ela.', es: 'Convierte cualquier texto en una película cinematográfica. Pega una historia, elige un estilo y mira cómo la IA le da vida.', de: 'Verwandle jeden Text in einen Kinofilm. Füge eine Geschichte ein, wähle einen Stil und sieh zu, wie KI sie zum Leben erweckt.', it: 'Trasforma qualsiasi testo in un film cinematografico. Incolla una storia, scegli uno stile e guarda l\'IA darle vita.', ru: 'Превратите любой текст в кинематографический фильм. Вставьте историю, выберите стиль и наблюдайте, как ИИ оживляет её.', ko: '어떤 텍스트든 영화로 변환하세요. 이야기를 붙여넣고, 스타일을 선택하고, AI가 생명을 불어넣는 것을 지켜보세요.', ja: 'どんなテキストも映画に変換。ストーリーを貼り付け、スタイルを選び、AIが命を吹き込む様子をご覧ください。' },
  'hero.cta': { en: 'Start Creating — Free', he: 'התחל ליצור — חינם', ar: 'ابدأ الإبداع — مجاناً', fr: 'Commencez à créer — Gratuit', zh: '开始创作 — 免费', pt: 'Comece a criar — Grátis', es: 'Empieza a crear — Gratis', de: 'Jetzt loslegen — Kostenlos', it: 'Inizia a creare — Gratis', ru: 'Начните создавать — Бесплатно', ko: '무료로 시작하기', ja: '無料で始める' },
  'hero.demo': { en: 'Watch Demo', he: 'צפה בהדגמה', ar: 'شاهد العرض', fr: 'Voir la démo', zh: '观看演示', pt: 'Ver demonstração', es: 'Ver demostración', de: 'Demo ansehen', it: 'Guarda la demo', ru: 'Смотреть демо', ko: '데모 보기', ja: 'デモを見る' },

  // ===== HOW IT WORKS =====
  'how.title': { en: 'From Imagination to Cinema\nin 4 Steps', he: 'מהדמיון לקולנוע\nב-4 צעדים', ar: 'من الخيال إلى السينما\nفي 4 خطوات', fr: 'De l\'imagination au cinéma\nen 4 étapes', zh: '从想象到电影\n只需4步', pt: 'Da imaginação ao cinema\nem 4 passos', es: 'De la imaginación al cine\nen 4 pasos', de: 'Von der Vorstellung zum Kino\nin 4 Schritten', it: 'Dall\'immaginazione al cinema\nin 4 passi', ru: 'От воображения к кино\nза 4 шага', ko: '상상에서 영화까지\n4단계로', ja: '想像から映画へ\n4ステップで' },
  'how.sub': { en: 'No film crew. No editing software. Just your story and AI magic.', he: 'בלי צוות צילום. בלי תוכנות עריכה. רק הסיפור שלך וקסם ה-AI.', ar: 'بدون فريق تصوير. بدون برامج مونتاج. فقط قصتك وسحر الذكاء الاصطناعي.', fr: 'Pas d\'équipe de tournage. Pas de logiciel de montage. Juste votre histoire et la magie de l\'IA.', zh: '无需摄制团队。无需剪辑软件。只需你的故事和AI魔法。', pt: 'Sem equipe de filmagem. Sem software de edição. Apenas sua história e a magia da IA.', es: 'Sin equipo de filmación. Sin software de edición. Solo tu historia y la magia de la IA.', de: 'Kein Filmteam. Keine Schnittsoftware. Nur deine Geschichte und KI-Magie.', it: 'Nessuna troupe. Nessun software di editing. Solo la tua storia e la magia dell\'IA.', ru: 'Без съёмочной группы. Без монтажных программ. Только ваша история и магия ИИ.', ko: '촬영팀도 필요 없고, 편집 소프트웨어도 필요 없습니다. 당신의 이야기와 AI 마법만 있으면 됩니다.', ja: '撮影クルー不要。編集ソフト不要。あなたの物語とAIの魔法だけ。' },
  'how.step1.title': { en: 'Write', he: 'כתוב', ar: 'اكتب', fr: 'Écrivez', zh: '编写', pt: 'Escreva', es: 'Escribe', de: 'Schreiben', it: 'Scrivi', ru: 'Напишите', ko: '작성', ja: '書く' },
  'how.step1.desc': { en: 'Paste your story, book excerpt, or describe your idea in any language', he: 'הדבק את הסיפור שלך, קטע מספר, או תאר את הרעיון בכל שפה', ar: 'الصق قصتك أو مقتطفاً من كتاب أو صف فكرتك بأي لغة', fr: 'Collez votre histoire, un extrait de livre, ou décrivez votre idée dans n\'importe quelle langue', zh: '粘贴你的故事、书摘，或用任何语言描述你的想法', pt: 'Cole sua história, trecho de livro ou descreva sua ideia em qualquer idioma', es: 'Pega tu historia, extracto de libro, o describe tu idea en cualquier idioma', de: 'Füge deine Geschichte, einen Buchauszug ein oder beschreibe deine Idee in jeder Sprache', it: 'Incolla la tua storia, un estratto di libro, o descrivi la tua idea in qualsiasi lingua', ru: 'Вставьте историю, отрывок из книги или опишите идею на любом языке', ko: '이야기, 책 발췌문을 붙여넣거나 아이디어를 설명하세요', ja: 'ストーリー、本の抜粋を貼り付け、またはアイデアを説明' },
  'how.step2.title': { en: 'Style', he: 'עצב', ar: 'صمّم', fr: 'Stylisez', zh: '风格化', pt: 'Estilize', es: 'Estiliza', de: 'Gestalten', it: 'Stilizza', ru: 'Стилизуйте', ko: '스타일', ja: 'スタイル' },
  'how.step2.desc': { en: 'Choose from 11 cinematic styles — Pixar, Realistic, Anime, LEGO, Comic Book, and more', he: 'בחר מ-11 סגנונות קולנועיים — פיקסר, ריאליסטי, אנימה, לגו, קומיקס, ועוד', ar: 'اختر من 11 أسلوباً سينمائياً — بيكسار، واقعي، أنيمي، ليغو، كوميكس، والمزيد', fr: 'Choisissez parmi 11 styles — Pixar, Réaliste, Anime, LEGO, Comics, et plus', zh: '从11种风格中选择 — 皮克斯、写实、动漫、乐高、漫画等', pt: 'Escolha entre 11 estilos — Pixar, Realista, Anime, LEGO, Quadrinhos, e mais', es: 'Elige entre 11 estilos — Pixar, Realista, Anime, LEGO, Cómic, y más', de: 'Wähle aus 11 Stilen — Pixar, Realistisch, Anime, LEGO, Comic, und mehr', it: 'Scegli tra 11 stili — Pixar, Realistico, Anime, LEGO, Fumetto, e altro', ru: 'Выберите из 11 стилей — Pixar, Реалистичный, Аниме, LEGO, Комикс, и другие', ko: '11가지 스타일 중 선택 — 픽사, 리얼리스틱, 애니메, 레고, 코믹 등', ja: '11のスタイルから選択 — ピクサー、リアル、アニメ、レゴ、コミック、他' },
  'how.step3.title': { en: 'Generate', he: 'צור', ar: 'أنشئ', fr: 'Générez', zh: '生成', pt: 'Gere', es: 'Genera', de: 'Generieren', it: 'Genera', ru: 'Создайте', ko: '생성', ja: '生成' },
  'how.step3.desc': { en: 'AI creates scene-by-scene with full continuity, dialogue, and soundtrack', he: 'AI יוצר סצנה אחרי סצנה עם המשכיות מלאה, דיאלוג ופסקול', ar: 'الذكاء الاصطناعي يُنشئ مشهداً تلو الآخر مع استمرارية كاملة وحوار وموسيقى', fr: 'L\'IA crée scène par scène avec une continuité totale, dialogue et bande sonore', zh: 'AI逐场景创建，保持完整连续性、对话和配乐', pt: 'A IA cria cena por cena com total continuidade, diálogo e trilha sonora', es: 'La IA crea escena por escena con continuidad total, diálogo y banda sonora', de: 'KI erstellt Szene für Szene mit voller Kontinuität, Dialog und Soundtrack', it: 'L\'IA crea scena per scena con piena continuità, dialogo e colonna sonora', ru: 'ИИ создаёт сцену за сценой с полной непрерывностью, диалогами и саундтреком', ko: 'AI가 완벽한 연속성, 대사, 사운드트랙으로 장면별 생성', ja: 'AIがシーンごとに完全な連続性、セリフ、サウンドトラックで作成' },
  'how.step4.title': { en: 'Watch', he: 'צפה', ar: 'شاهد', fr: 'Regardez', zh: '观看', pt: 'Assista', es: 'Mira', de: 'Anschauen', it: 'Guarda', ru: 'Смотрите', ko: '감상', ja: '視聴' },
  'how.step4.desc': { en: 'Preview, fine-tune, and export your complete film in multiple languages', he: 'צפה בתצוגה מקדימה, כוונן וייצא את הסרט המלא במספר שפות', ar: 'شاهد المعاينة، عدّل بدقة، وصدّر فيلمك الكامل بعدة لغات', fr: 'Prévisualisez, affinez et exportez votre film complet en plusieurs langues', zh: '预览、微调并导出多语言完整影片', pt: 'Pré-visualize, ajuste e exporte seu filme completo em vários idiomas', es: 'Previsualiza, ajusta y exporta tu película completa en varios idiomas', de: 'Vorschau, Feinabstimmung und Export deines Films in mehreren Sprachen', it: 'Anteprima, perfeziona ed esporta il tuo film completo in più lingue', ru: 'Предпросмотр, доработка и экспорт фильма на нескольких языках', ko: '미리보기, 미세 조정 후 여러 언어로 완성 영화 내보내기', ja: 'プレビュー、微調整、複数言語での映画エクスポート' },

  // ===== USE CASES =====
  'cases.title': { en: 'One Platform,\nInfinite Possibilities', he: 'פלטפורמה אחת,\nאינסוף אפשרויות', ar: 'منصة واحدة،\nإمكانيات لا حدود لها', fr: 'Une plateforme,\ndes possibilités infinies', zh: '一个平台，\n无限可能', pt: 'Uma plataforma,\npossibilidades infinitas', es: 'Una plataforma,\nposibilidades infinitas', de: 'Eine Plattform,\nunendliche Möglichkeiten', it: 'Una piattaforma,\npossibilità infinite', ru: 'Одна платформа,\nбезграничные возможности', ko: '하나의 플랫폼,\n무한한 가능성', ja: '一つのプラットフォーム、\n無限の可能性' },
  'cases.sub': { en: 'Whether you\'re an author, educator, marketer, or filmmaker — Cinema AI Studio is built for you.', he: 'בין אם אתה סופר, מחנך, משווק או יוצר סרטים — Cinema AI Studio נבנה בשבילך.', ar: 'سواء كنت كاتباً أو معلماً أو مسوقاً أو صانع أفلام — Cinema AI Studio مصمم لك.', fr: 'Que vous soyez auteur, éducateur, marketeur ou cinéaste — Cinema AI Studio est fait pour vous.', zh: '无论你是作家、教育者、营销人员还是电影人 — Cinema AI Studio 为你而建。', pt: 'Seja você autor, educador, profissional de marketing ou cineasta — Cinema AI Studio foi feito para você.', es: 'Ya seas autor, educador, profesional del marketing o cineasta — Cinema AI Studio está hecho para ti.', de: 'Ob Autor, Pädagoge, Marketer oder Filmemacher — Cinema AI Studio ist für dich gebaut.', it: 'Che tu sia autore, educatore, marketer o cineasta — Cinema AI Studio è costruito per te.', ru: 'Писатель, преподаватель, маркетолог или кинематографист — Cinema AI Studio создана для вас.', ko: '작가, 교육자, 마케터, 영화 제작자 — Cinema AI Studio는 당신을 위해 만들어졌습니다.', ja: '作家、教育者、マーケター、映画制作者 — Cinema AI Studioはあなたのために作られました。' },
  'cases.authors': { en: 'Authors & Publishers', he: 'סופרים ומו"לים', ar: 'المؤلفون والناشرون', fr: 'Auteurs & Éditeurs', zh: '作家与出版商', pt: 'Autores & Editoras', es: 'Autores & Editores', de: 'Autoren & Verlage', it: 'Autori & Editori', ru: 'Авторы и издатели', ko: '작가 & 출판사', ja: '作家・出版社' },
  'cases.authorsDesc': { en: 'Turn your novel into a visual trailer or animated series', he: 'הפוך את הרומן שלך לטריילר ויזואלי או סדרה מונפשת', ar: 'حوّل روايتك إلى عرض مرئي أو مسلسل رسوم متحركة', fr: 'Transformez votre roman en bande-annonce visuelle ou série animée', zh: '将小说转化为视觉预告片或动画系列', pt: 'Transforme seu romance em trailer visual ou série animada', es: 'Convierte tu novela en tráiler visual o serie animada', de: 'Verwandle deinen Roman in einen visuellen Trailer oder eine Animationsserie', it: 'Trasforma il tuo romanzo in un trailer visivo o una serie animata', ru: 'Превратите роман в видео-трейлер или анимационный сериал', ko: '소설을 비주얼 트레일러나 애니메이션 시리즈로 변환', ja: '小説をビジュアルトレーラーやアニメシリーズに変換' },
  'cases.educators': { en: 'Educators', he: 'מחנכים', ar: 'المعلمون', fr: 'Éducateurs', zh: '教育工作者', pt: 'Educadores', es: 'Educadores', de: 'Pädagogen', it: 'Educatori', ru: 'Преподаватели', ko: '교육자', ja: '教育者' },
  'cases.educatorsDesc': { en: 'Create animated lessons that captivate students in any language', he: 'צור שיעורים מונפשים שמרתקים תלמידים בכל שפה', ar: 'أنشئ دروساً متحركة تأسر الطلاب بأي لغة', fr: 'Créez des leçons animées qui captivent les élèves dans toute langue', zh: '创建能够吸引学生的多语言动画课程', pt: 'Crie aulas animadas que cativam alunos em qualquer idioma', es: 'Crea lecciones animadas que cautiven a los estudiantes en cualquier idioma', de: 'Erstelle animierte Lektionen, die Schüler in jeder Sprache fesseln', it: 'Crea lezioni animate che affascinano gli studenti in qualsiasi lingua', ru: 'Создавайте анимированные уроки, увлекающие учеников на любом языке', ko: '어떤 언어로든 학생들을 사로잡는 애니메이션 수업 제작', ja: 'どの言語でも生徒を魅了するアニメーション授業を作成' },
  'cases.marketing': { en: 'Marketing Teams', he: 'צוותי שיווק', ar: 'فرق التسويق', fr: 'Équipes Marketing', zh: '营销团队', pt: 'Equipes de Marketing', es: 'Equipos de Marketing', de: 'Marketing-Teams', it: 'Team Marketing', ru: 'Маркетинговые команды', ko: '마케팅 팀', ja: 'マーケティングチーム' },
  'cases.marketingDesc': { en: 'Produce ad campaigns and branded content in minutes, not months', he: 'הפק קמפיינים פרסומיים ותוכן ממותג בדקות, לא חודשים', ar: 'أنتج حملات إعلانية ومحتوى مميزاً في دقائق وليس أشهر', fr: 'Produisez des campagnes publicitaires en minutes, pas en mois', zh: '几分钟而非几个月即可制作广告活动和品牌内容', pt: 'Produza campanhas publicitárias e conteúdo de marca em minutos, não meses', es: 'Produce campañas publicitarias y contenido de marca en minutos, no meses', de: 'Produziere Werbekampagnen und Markeninhalte in Minuten, nicht Monaten', it: 'Produci campagne pubblicitarie e contenuti brandizzati in minuti, non mesi', ru: 'Создавайте рекламные кампании за минуты, а не месяцы', ko: '몇 달이 아닌 몇 분 만에 광고 캠페인과 브랜드 콘텐츠 제작', ja: '数ヶ月ではなく数分で広告キャンペーンを制作' },
  'cases.creators': { en: 'Content Creators', he: 'יוצרי תוכן', ar: 'صناع المحتوى', fr: 'Créateurs de contenu', zh: '内容创作者', pt: 'Criadores de conteúdo', es: 'Creadores de contenido', de: 'Content Creator', it: 'Content Creator', ru: 'Контент-мейкеры', ko: '콘텐츠 크리에이터', ja: 'コンテンツクリエイター' },
  'cases.creatorsDesc': { en: 'Generate YouTube-quality cinematic videos from a simple script', he: 'צור סרטונים קולנועיים באיכות יוטיוב מתסריט פשוט', ar: 'أنشئ فيديوهات سينمائية بجودة يوتيوب من نص بسيط', fr: 'Générez des vidéos cinématographiques de qualité YouTube à partir d\'un simple script', zh: '通过简单脚本生成YouTube品质的电影视频', pt: 'Gere vídeos cinematográficos de qualidade YouTube a partir de um simples roteiro', es: 'Genera videos cinematográficos de calidad YouTube a partir de un simple guión', de: 'Erstelle YouTube-qualitative Kinovideos aus einem einfachen Skript', it: 'Genera video cinematografici di qualità YouTube da un semplice script', ru: 'Создавайте кинематографические видео YouTube-качества из простого сценария', ko: '간단한 스크립트로 유튜브급 시네마틱 영상 제작', ja: 'シンプルな脚本からYouTube品質の映画的動画を生成' },
  'cases.studios': { en: 'Production Studios', he: 'סטודיו הפקה', ar: 'استوديوهات الإنتاج', fr: 'Studios de production', zh: '制作工作室', pt: 'Estúdios de produção', es: 'Estudios de producción', de: 'Produktionsstudios', it: 'Studi di produzione', ru: 'Продакшн-студии', ko: '프로덕션 스튜디오', ja: 'プロダクションスタジオ' },
  'cases.studiosDesc': { en: 'Pre-visualize entire scenes before expensive shoots', he: 'צפה בתצוגה מקדימה של סצנות לפני צילומים יקרים', ar: 'تصور المشاهد مسبقاً قبل التصوير المكلف', fr: 'Pré-visualisez des scènes entières avant des tournages coûteux', zh: '在昂贵拍摄前预览完整场景', pt: 'Pré-visualize cenas inteiras antes de filmagens caras', es: 'Pre-visualiza escenas completas antes de rodajes costosos', de: 'Visualisiere ganze Szenen vor teuren Dreharbeiten', it: 'Pre-visualizza scene intere prima di riprese costose', ru: 'Предвизуализируйте сцены перед дорогими съёмками', ko: '비용이 많이 드는 촬영 전에 전체 장면을 사전 시각화', ja: '高額な撮影の前にシーン全体をプレビジュアライズ' },
  'cases.business': { en: 'Businesses', he: 'עסקים', ar: 'الشركات', fr: 'Entreprises', zh: '企业', pt: 'Empresas', es: 'Empresas', de: 'Unternehmen', it: 'Aziende', ru: 'Бизнес', ko: '기업', ja: 'ビジネス' },
  'cases.businessDesc': { en: 'Internal training videos, product demos, and investor pitch decks', he: 'סרטוני הדרכה פנימיים, הדגמות מוצר ומצגות למשקיעים', ar: 'فيديوهات تدريب داخلية وعروض منتجات وعروض للمستثمرين', fr: 'Vidéos de formation interne, démos produit et présentations investisseurs', zh: '内部培训视频、产品演示和投资者演示', pt: 'Vídeos de treinamento, demonstrações de produto e apresentações para investidores', es: 'Videos de capacitación, demos de producto y presentaciones para inversores', de: 'Interne Schulungsvideos, Produktdemos und Investorenpräsentationen', it: 'Video di formazione interna, demo prodotto e presentazioni per investitori', ru: 'Обучающие видео, демо продуктов и презентации для инвесторов', ko: '사내 교육 영상, 제품 데모, 투자자 프레젠테이션', ja: '社内トレーニング動画、製品デモ、投資家プレゼン' },

  // ===== STYLES =====
  'styles.title': { en: '11 Cinematic Styles', he: '11 סגנונות קולנועיים', ar: '11 أسلوباً سينمائياً', fr: '11 styles cinématographiques', zh: '11种电影风格', pt: '11 estilos cinematográficos', es: '11 estilos cinematográficos', de: '11 Filmstile', it: '11 stili cinematografici', ru: '11 кинематографических стилей', ko: '11가지 영화 스타일', ja: '11の映画スタイル' },
  'styles.sub': { en: 'From Pixar to Anime, LEGO to Claymation — every visual world at your fingertips', he: 'מפיקסר עד אנימה, מלגו עד פלסטלינה — כל עולם ויזואלי בקצות האצבעות', ar: 'من بيكسار إلى الأنيمي، من ليغو إلى الصلصال — كل عالم بصري في متناول يدك', fr: 'De Pixar à l\'Anime, du LEGO au Claymation — chaque univers visuel au bout des doigts', zh: '从皮克斯到动漫，从乐高到黏土动画——每一个视觉世界尽在指尖', pt: 'De Pixar a Anime, LEGO a Claymation — cada mundo visual na ponta dos dedos', es: 'De Pixar a Anime, LEGO a Claymation — cada mundo visual a tu alcance', de: 'Von Pixar bis Anime, LEGO bis Knetfiguren — jede visuelle Welt auf Knopfdruck', it: 'Da Pixar ad Anime, LEGO a Claymation — ogni mondo visivo a portata di mano', ru: 'От Pixar до Аниме, от LEGO до пластилина — весь визуальный мир под рукой', ko: '픽사에서 애니메, 레고에서 클레이모션까지 — 모든 비주얼 세계가 손끝에', ja: 'ピクサーからアニメ、レゴからクレイまで — あらゆるビジュアルワールド' },

  // ===== IDEA SHOWCASE =====
  'ideas.badge': { en: 'Inspiration Gallery', he: 'גלריית השראה', ar: 'معرض الإلهام', fr: 'Galerie d\'inspiration', zh: '灵感画廊', pt: 'Galeria de inspiração', es: 'Galería de inspiración', de: 'Inspirations-Galerie', it: 'Galleria di ispirazione', ru: 'Галерея вдохновения', ko: '영감 갤러리', ja: 'インスピレーションギャラリー' },
  'ideas.title': { en: 'What Will You Create?', he: 'מה תיצור היום?', ar: 'ماذا ستبتكر؟', fr: 'Que allez-vous créer ?', zh: '你将创造什么？', pt: 'O que você vai criar?', es: '¿Qué crearás?', de: 'Was wirst du erschaffen?', it: 'Cosa creerai?', ru: 'Что вы создадите?', ko: '무엇을 만드시겠습니까?', ja: '何を創りますか？' },
  'ideas.sub': { en: 'Explore film ideas — click any to start creating your version instantly', he: 'חקור רעיונות לסרטים — לחץ על כל אחד כדי להתחיל ליצור את הגרסה שלך מיד', ar: 'استكشف أفكار الأفلام — انقر على أي منها لبدء إنشاء نسختك فوراً', fr: 'Explorez des idées de films — cliquez pour commencer à créer votre version', zh: '探索电影创意——点击任意一个即可开始创作您的版本', pt: 'Explore ideias de filmes — clique em qualquer um para começar a criar', es: 'Explora ideas de películas — haz clic para empezar a crear tu versión', de: 'Erkunde Filmideen — klicke auf eine, um sofort deine Version zu erstellen', it: 'Esplora idee per film — clicca per iniziare a creare la tua versione', ru: 'Исследуйте идеи фильмов — нажмите на любую, чтобы начать создание', ko: '영화 아이디어 탐색 — 클릭하여 바로 버전 제작 시작', ja: '映画のアイデアを探索 — クリックして即座に制作開始' },
  'ideas.tryThis': { en: 'Try this idea →', he: 'נסה את הרעיון →', ar: 'جرب هذه الفكرة →', fr: 'Essayez cette idée →', zh: '试试这个创意 →', pt: 'Tente esta ideia →', es: 'Prueba esta idea →', de: 'Diese Idee ausprobieren →', it: 'Prova questa idea →', ru: 'Попробовать эту идею →', ko: '이 아이디어 시도하기 →', ja: 'このアイデアを試す →' },

  'ideas.children': { en: 'Children\'s Stories', he: 'סיפורי ילדים', ar: 'قصص الأطفال', fr: 'Histoires pour enfants', zh: '儿童故事', pt: 'Histórias infantis', es: 'Historias infantiles', de: 'Kindergeschichten', it: 'Storie per bambini', ru: 'Детские истории', ko: '어린이 이야기', ja: '子供向けストーリー' },
  'ideas.childrenDesc': { en: 'Amazing Pixar-style characters come alive — magical treehouse adventures, friendly dragons, and glowing storybooks', he: 'דמויות פיקסר מדהימות מתעוררות לחיים — הרפתקאות בית עץ קסום, דרקונים ידידותיים וספרי סיפורים זוהרים', ar: 'شخصيات بيكسار المذهلة تنبض بالحياة — مغامرات بيت الشجرة السحري والتنانين الودودة', fr: 'Des personnages Pixar prennent vie — aventures dans une cabane magique, dragons amicaux', zh: '惊人的皮克斯角色活了过来——魔法树屋冒险、友好的龙和发光的故事书', pt: 'Personagens incríveis estilo Pixar ganham vida — aventuras na casa da árvore mágica', es: 'Increíbles personajes estilo Pixar cobran vida — aventuras en la casa del árbol mágica', de: 'Erstaunliche Pixar-Figuren erwachen zum Leben — magische Baumhaus-Abenteuer', it: 'Incredibili personaggi Pixar prendono vita — avventure nella casa sull\'albero magica', ru: 'Удивительные персонажи в стиле Pixar оживают — приключения в волшебном домике на дереве', ko: '놀라운 픽사 스타일 캐릭터가 살아납니다 — 마법 트리하우스 모험', ja: '素晴らしいピクサースタイルのキャラクターが生き生きと — 魔法のツリーハウスの冒険' },

  'ideas.documentary': { en: 'Documentary Films', he: 'סרטי דוקומנטרי', ar: 'الأفلام الوثائقية', fr: 'Films documentaires', zh: '纪录片', pt: 'Documentários', es: 'Documentales', de: 'Dokumentarfilme', it: 'Documentari', ru: 'Документальные фильмы', ko: '다큐멘터리', ja: 'ドキュメンタリー' },
  'ideas.documentaryDesc': { en: 'Hyper-realistic dinosaurs, ancient civilizations, and nature — National Geographic quality AI films', he: 'דינוזאורים היפר-ריאליסטיים, ציוויליזציות עתיקות וטבע — סרטי AI באיכות נשיונל ג\'אוגרפיק', ar: 'ديناصورات واقعية للغاية وحضارات قديمة وطبيعة — أفلام AI بجودة ناشيونال جيوغرافيك', fr: 'Dinosaures hyper-réalistes, civilisations anciennes — qualité National Geographic', zh: '超逼真恐龙、古代文明和自然——国家地理品质的AI电影', pt: 'Dinossauros hiper-realistas, civilizações antigas — qualidade National Geographic', es: 'Dinosaurios hiper-realistas, civilizaciones antiguas — calidad National Geographic', de: 'Hyperrealistische Dinosaurier, antike Zivilisationen — National Geographic Qualität', it: 'Dinosauri iper-realistici, civiltà antiche — qualità National Geographic', ru: 'Гиперреалистичные динозавры, древние цивилизации — качество National Geographic', ko: '초현실적 공룡, 고대 문명 — 내셔널 지오그래픽 품질 AI 영화', ja: '超リアルな恐竜、古代文明 — ナショナルジオグラフィック品質のAI映画' },

  'ideas.eduMath': { en: 'Math Education', he: 'לימודי חשבון', ar: 'تعليم الرياضيات', fr: 'Éducation mathématique', zh: '数学教育', pt: 'Educação matemática', es: 'Educación matemática', de: 'Mathematik-Bildung', it: 'Educazione matematica', ru: 'Математическое образование', ko: '수학 교육', ja: '数学教育' },
  'ideas.eduMathDesc': { en: 'Holographic 3D geometry, robot teachers, and interactive lessons that make math fun for every student', he: 'גיאומטריה הולוגרפית תלת-ממדית, רובוטים מורים ושיעורים אינטראקטיביים שהופכים חשבון לכיף', ar: 'هندسة ثلاثية الأبعاد هولوغرافية ومعلمون روبوت ودروس تفاعلية تجعل الرياضيات ممتعة', fr: 'Géométrie 3D holographique, robots enseignants et leçons interactives qui rendent les maths amusantes', zh: '全息3D几何、机器人教师和互动课程，让数学变得有趣', pt: 'Geometria 3D holográfica, professores robôs e aulas interativas que tornam matemática divertida', es: 'Geometría 3D holográfica, profesores robot y lecciones interactivas que hacen las mates divertidas', de: 'Holographische 3D-Geometrie, Roboterlehrer und interaktive Lektionen', it: 'Geometria 3D olografica, insegnanti robot e lezioni interattive che rendono la matematica divertente', ru: 'Голографическая 3D-геометрия, роботы-учителя и интерактивные уроки', ko: '홀로그래픽 3D 기하학, 로봇 교사, 수학을 재미있게 만드는 인터랙티브 수업', ja: 'ホログラフィック3D幾何学、ロボット教師、数学を楽しくするインタラクティブ授業' },

  'ideas.eduScience': { en: 'Science Education', he: 'לימודי מדעים', ar: 'تعليم العلوم', fr: 'Éducation scientifique', zh: '科学教育', pt: 'Educação científica', es: 'Educación científica', de: 'Naturwissenschaften', it: 'Educazione scientifica', ru: 'Научное образование', ko: '과학 교육', ja: '科学教育' },
  'ideas.eduScienceDesc': { en: 'Miniature solar systems, DNA helixes, and bubbling experiments — science lessons that spark wonder', he: 'מערכות שמש מיניאטוריות, סלילי DNA וניסויים מבעבעים — שיעורי מדעים שמעוררים פליאה', ar: 'أنظمة شمسية مصغرة وحلزونات DNA وتجارب فقاعية — دروس علوم تثير الدهشة', fr: 'Systèmes solaires miniatures, hélices d\'ADN et expériences — des cours de sciences qui émerveillent', zh: '微型太阳系、DNA螺旋和冒泡实验——激发好奇心的科学课', pt: 'Sistemas solares em miniatura, hélices de DNA e experimentos — aulas de ciências que inspiram', es: 'Sistemas solares en miniatura, hélices de ADN y experimentos — ciencia que inspira asombro', de: 'Miniatur-Sonnensysteme, DNA-Helices und Experimente — Wissenschaft die begeistert', it: 'Sistemi solari in miniatura, eliche di DNA ed esperimenti — lezioni di scienze che ispirano meraviglia', ru: 'Миниатюрные солнечные системы, спирали ДНК и опыты — уроки науки, вызывающие восторг', ko: '미니어처 태양계, DNA 나선, 실험 — 경이로움을 불러일으키는 과학 수업', ja: 'ミニチュア太陽系、DNAらせん、泡立つ実験 — 驚きを呼ぶ科学授業' },

  'ideas.ted': { en: 'TED-Style Lectures', he: 'הרצאות בסגנון TED', ar: 'محاضرات بأسلوب TED', fr: 'Conférences style TED', zh: 'TED风格讲座', pt: 'Palestras estilo TED', es: 'Conferencias estilo TED', de: 'TED-Style Vorträge', it: 'Conferenze stile TED', ru: 'Лекции в стиле TED', ko: 'TED 스타일 강연', ja: 'TEDスタイル講演' },
  'ideas.tedDesc': { en: 'Professional stage presentations with stunning data visualizations and cinematic camera work', he: 'מצגות במה מקצועיות עם ויזואליזציות נתונים מרהיבות ועבודת מצלמה קולנועית', ar: 'عروض مسرحية احترافية مع تصورات بيانات مذهلة وتصوير سينمائي', fr: 'Présentations professionnelles avec visualisations de données et caméra cinématographique', zh: '专业舞台演讲，配以令人惊叹的数据可视化和电影级摄影', pt: 'Apresentações profissionais com visualizações de dados impressionantes e câmera cinematográfica', es: 'Presentaciones profesionales con visualizaciones de datos impresionantes y cámara cinematográfica', de: 'Professionelle Bühnenpräsentationen mit beeindruckenden Datenvisualisierungen', it: 'Presentazioni professionali con visualizzazioni dati mozzafiato e riprese cinematografiche', ru: 'Профессиональные сценические презентации с потрясающей визуализацией данных', ko: '놀라운 데이터 시각화와 영화적 카메라 워크를 갖춘 전문 무대 프레젠테이션', ja: '見事なデータビジュアライゼーションと映画的カメラワークのプロステージプレゼンテーション' },

  'ideas.advertising': { en: 'Advertisements', he: 'פרסומות', ar: 'الإعلانات', fr: 'Publicités', zh: '广告', pt: 'Publicidade', es: 'Publicidad', de: 'Werbung', it: 'Pubblicità', ru: 'Реклама', ko: '광고', ja: '広告' },
  'ideas.advertisingDesc': { en: 'Luxury product shots, dramatic lighting, and high-end commercial quality — all generated by AI', he: 'צילומי מוצר יוקרתיים, תאורה דרמטית ואיכות פרסומת יוקרתית — הכל נוצר על ידי AI', ar: 'لقطات منتجات فاخرة وإضاءة درامية وجودة إعلانية راقية — كلها من إنتاج الذكاء الاصطناعي', fr: 'Photos de produits luxueux, éclairage dramatique — qualité commerciale haut de gamme', zh: '奢华产品拍摄、戏剧性灯光和高端商业品质——全部由AI生成', pt: 'Fotos de produtos de luxo, iluminação dramática e qualidade comercial premium — tudo gerado por IA', es: 'Fotos de productos de lujo, iluminación dramática y calidad comercial premium — todo generado por IA', de: 'Luxus-Produktfotos, dramatische Beleuchtung und High-End-Werbequalität — alles KI-generiert', it: 'Scatti di prodotti di lusso, illuminazione drammatica e qualità commerciale premium — tutto generato da IA', ru: 'Роскошные снимки продукции, драматическое освещение и премиальное рекламное качество', ko: '럭셔리 제품 촬영, 드라마틱한 조명, 하이엔드 광고 품질 — 모두 AI로 생성', ja: '高級製品撮影、ドラマチックな照明、ハイエンド広告品質 — すべてAI生成' },

  'ideas.business': { en: 'Business & Corporate', he: 'עסקים וחברות', ar: 'الأعمال والشركات', fr: 'Business & Corporate', zh: '商业与企业', pt: 'Negócios & Corporativo', es: 'Negocios & Corporativo', de: 'Business & Corporate', it: 'Business & Corporate', ru: 'Бизнес и корпорации', ko: '비즈니스 & 기업', ja: 'ビジネス＆企業' },
  'ideas.businessDesc': { en: 'Holographic product demos, investor pitches, and training videos in premium corporate settings', he: 'הדגמות מוצר הולוגרפיות, מצגות למשקיעים וסרטוני הדרכה בסביבה עסקית יוקרתית', ar: 'عروض منتجات هولوغرافية وعروض للمستثمرين وفيديوهات تدريب في بيئات شركات فاخرة', fr: 'Démos de produits holographiques, présentations investisseurs et vidéos de formation', zh: '全息产品演示、投资者演讲和高端企业环境中的培训视频', pt: 'Demos de produtos holográficos, apresentações para investidores e vídeos de treinamento', es: 'Demos de productos holográficos, presentaciones para inversores y videos de capacitación', de: 'Holographische Produktdemos, Investorenpräsentationen und Schulungsvideos', it: 'Demo di prodotti olografici, presentazioni per investitori e video di formazione', ru: 'Голографические демо продуктов, презентации инвесторам и обучающие видео', ko: '홀로그래픽 제품 데모, 투자자 피칭, 프리미엄 기업 환경에서의 교육 영상', ja: 'ホログラフィック製品デモ、投資家プレゼン、プレミアム企業環境のトレーニング動画' },

  'ideas.agency': { en: 'Ad Agencies', he: 'סוכנויות פרסום', ar: 'وكالات الإعلان', fr: 'Agences publicitaires', zh: '广告公司', pt: 'Agências de publicidade', es: 'Agencias de publicidad', de: 'Werbeagenturen', it: 'Agenzie pubblicitarie', ru: 'Рекламные агентства', ko: '광고 에이전시', ja: '広告代理店' },
  'ideas.agencyDesc': { en: 'Campaign concepts, mood boards, and creative pitches — bring any idea to life in minutes', he: 'קונספטים לקמפיינים, לוחות השראה ומצגות יצירתיות — הפוך כל רעיון למציאות בדקות', ar: 'مفاهيم الحملات ولوحات المزاج والعروض الإبداعية — أحيِ أي فكرة في دقائق', fr: 'Concepts de campagne, mood boards et pitches créatifs — donnez vie à toute idée en minutes', zh: '活动概念、情绪板和创意提案——几分钟内将任何想法变为现实', pt: 'Conceitos de campanha, mood boards e pitches criativos — dê vida a qualquer ideia em minutos', es: 'Conceptos de campaña, mood boards y pitches creativos — da vida a cualquier idea en minutos', de: 'Kampagnenkonzepte, Moodboards und kreative Pitches — in Minuten zum Leben erweckt', it: 'Concetti di campagna, mood board e pitch creativi — dai vita a qualsiasi idea in minuti', ru: 'Концепции кампаний, мудборды и креативные питчи — воплотите любую идею за минуты', ko: '캠페인 컨셉, 무드보드, 크리에이티브 피칭 — 몇 분 만에 아이디어를 현실로', ja: 'キャンペーンコンセプト、ムードボード、クリエイティブピッチ — 数分でアイデアを実現' },

  'ideas.creator': { en: 'Content Creators', he: 'יוצרי תוכן', ar: 'صناع المحتوى', fr: 'Créateurs de contenu', zh: '内容创作者', pt: 'Criadores de conteúdo', es: 'Creadores de contenido', de: 'Content Creator', it: 'Content Creator', ru: 'Контент-мейкеры', ko: '콘텐츠 크리에이터', ja: 'コンテンツクリエイター' },
  'ideas.creatorDesc': { en: 'YouTube intros, thumbnail scenes, and cinematic B-roll — level up your content with AI-generated video', he: 'פתיחות יוטיוב, סצנות לתמונות ממוזערות ו-B-roll קולנועי — שדרג את התוכן שלך עם וידאו AI', ar: 'مقدمات يوتيوب ومشاهد صور مصغرة و B-roll سينمائي — ارتقِ بمحتواك مع فيديو AI', fr: 'Intros YouTube, scènes miniatures et B-roll cinématographique — améliorez votre contenu', zh: 'YouTube片头、缩略图场景和电影级B-roll——用AI生成的视频提升你的内容', pt: 'Intros do YouTube, cenas de thumbnail e B-roll cinematográfico — eleve seu conteúdo com vídeo AI', es: 'Intros de YouTube, escenas de miniatura y B-roll cinematográfico — sube de nivel tu contenido', de: 'YouTube-Intros, Thumbnail-Szenen und filmischer B-Roll — Content mit KI-Video aufwerten', it: 'Intro YouTube, scene per miniature e B-roll cinematografico — migliora i tuoi contenuti con video AI', ru: 'Интро для YouTube, сцены для превью и кинематографический B-roll — прокачайте контент с AI-видео', ko: '유튜브 인트로, 썸네일 장면, 시네마틱 B-roll — AI 생성 영상으로 콘텐츠 레벨업', ja: 'YouTubeイントロ、サムネイルシーン、映画的Bロール — AI生成動画でコンテンツをレベルアップ' },

  'ideas.cooking': { en: 'Cooking Shows', he: 'תוכניות בישול', ar: 'برامج الطبخ', fr: 'Émissions de cuisine', zh: '烹饪节目', pt: 'Programas de culinária', es: 'Programas de cocina', de: 'Kochshows', it: 'Show di cucina', ru: 'Кулинарные шоу', ko: '요리 프로그램', ja: '料理番組' },
  'ideas.cookingDesc': { en: 'Flying ingredients, dramatic steam, and sizzling pans — spectacular food cinematography from text', he: 'מרכיבים מעופפים, קיטור דרמטי ומחבתות מרתיחות — צילום אוכל מרהיב מטקסט', ar: 'مكونات طائرة وبخار درامي ومقالي ساخنة — تصوير طعام مذهل من النص', fr: 'Ingrédients volants, vapeur dramatique — cinématographie culinaire spectaculaire à partir de texte', zh: '飞舞的食材、戏剧性的蒸汽和滋滋作响的平底锅——从文字生成的壮观美食摄影', pt: 'Ingredientes voando, vapor dramático e panelas chiando — cinematografia gastronômica espetacular', es: 'Ingredientes volando, vapor dramático y sartenes chisporroteantes — cinematografía gastronómica', de: 'Fliegende Zutaten, dramatischer Dampf und brutzelnde Pfannen — spektakuläre Food-Kinematographie', it: 'Ingredienti volanti, vapore drammatico e padelle sfrigolanti — cinematografia culinaria spettacolare', ru: 'Летающие ингредиенты, эффектный пар и шипящие сковороды — впечатляющая кино-кулинария', ko: '날아다니는 재료, 드라마틱한 증기, 지글거리는 팬 — 텍스트에서 만드는 화려한 푸드 시네마', ja: '飛び交う食材、ドラマチックな蒸気、ジュージューのフライパン — テキストから壮観なフード撮影' },

  'ideas.travel': { en: 'Travel & Adventure', he: 'טיולים והרפתקאות', ar: 'السفر والمغامرات', fr: 'Voyages & Aventure', zh: '旅行与冒险', pt: 'Viagens & Aventura', es: 'Viajes & Aventura', de: 'Reisen & Abenteuer', it: 'Viaggi & Avventura', ru: 'Путешествия и приключения', ko: '여행 & 모험', ja: '旅行＆アドベンチャー' },
  'ideas.travelDesc': { en: 'Breathtaking landscapes, mountain peaks at sunrise, and epic exploration — National Geographic quality', he: 'נופים עוצרי נשימה, פסגות הרים בזריחה והרפתקאות אפיות — איכות נשיונל ג\'אוגרפיק', ar: 'مناظر طبيعية خلابة وقمم جبال عند الشروق واستكشاف ملحمي — جودة ناشيونال جيوغرافيك', fr: 'Paysages à couper le souffle, sommets au lever du soleil — qualité National Geographic', zh: '令人叹为观止的风景、日出时的山峰和史诗般的探险——国家地理品质', pt: 'Paisagens de tirar o fôlego, picos ao nascer do sol — qualidade National Geographic', es: 'Paisajes impresionantes, picos al amanecer — calidad National Geographic', de: 'Atemberaubende Landschaften, Berggipfel bei Sonnenaufgang — National Geographic Qualität', it: 'Paesaggi mozzafiato, vette all\'alba — qualità National Geographic', ru: 'Захватывающие пейзажи, горные вершины на рассвете — качество National Geographic', ko: '숨막히는 풍경, 일출의 산봉우리, 장엄한 탐험 — 내셔널 지오그래픽 품질', ja: '息をのむ風景、日の出の山頂、壮大な探検 — ナショナルジオグラフィック品質' },

  'ideas.music': { en: 'Music & Concerts', he: 'מוזיקה והופעות', ar: 'الموسيقى والحفلات', fr: 'Musique & Concerts', zh: '音乐与演唱会', pt: 'Música & Concertos', es: 'Música & Conciertos', de: 'Musik & Konzerte', it: 'Musica & Concerti', ru: 'Музыка и концерты', ko: '음악 & 콘서트', ja: '音楽＆コンサート' },
  'ideas.musicDesc': { en: 'Laser shows, pyrotechnics, and electrifying concert atmospheres — epic music visuals from a script', he: 'מופעי לייזר, זיקוקים ואווירת הופעות חשמלית — ויזואלים מוזיקליים אפיים מתסריט', ar: 'عروض ليزر وألعاب نارية وأجواء حفلات كهربائية — مرئيات موسيقية ملحمية من نص', fr: 'Spectacles laser, pyrotechnie et atmosphères de concert — visuels musicaux épiques', zh: '激光秀、烟火和电气化的音乐会氛围——从剧本创建的史诗音乐视觉', pt: 'Shows de laser, pirotecnia e atmosferas de concerto eletrizantes — visuais musicais épicos', es: 'Shows de láser, pirotecnia y atmósferas de concierto electrizantes — visuales musicales épicos', de: 'Lasershows, Pyrotechnik und elektrisierende Konzertatmosphäre — epische Musikvisualisierungen', it: 'Spettacoli laser, pirotecnica e atmosfere da concerto elettrizzanti — visual musicali epici', ru: 'Лазерные шоу, пиротехника и захватывающая атмосфера концертов — эпическая музыкальная визуализация', ko: '레이저 쇼, 불꽃놀이, 전율의 콘서트 분위기 — 스크립트에서 만드는 장엄한 뮤직 비주얼', ja: 'レーザーショー、花火、電撃的なコンサート雰囲気 — 脚本から壮大な音楽ビジュアル' },

  // ===== GLOBAL REACH =====
  'global.title': { en: 'One Film,\nEvery Language', he: 'סרט אחד,\nכל שפה', ar: 'فيلم واحد،\nكل لغة', fr: 'Un film,\ntoutes les langues', zh: '一部电影，\n所有语言', pt: 'Um filme,\ntodos os idiomas', es: 'Una película,\ntodos los idiomas', de: 'Ein Film,\njede Sprache', it: 'Un film,\nogni lingua', ru: 'Один фильм,\nвсе языки', ko: '하나의 영화,\n모든 언어', ja: '一つの映画、\nすべての言語' },
  'global.sub': { en: 'Create once, reach the world. 12 interface languages. Multi-language dubbing. Full RTL support.', he: 'צור פעם אחת, הגע לעולם. 12 שפות ממשק. דיבוב רב-לשוני. תמיכה מלאה ב-RTL.', ar: 'أنشئ مرة واحدة، وصل للعالم. 12 لغة واجهة. دبلجة متعددة اللغات. دعم كامل لـ RTL.', fr: 'Créez une fois, atteignez le monde. 12 langues d\'interface. Doublage multilingue. Support RTL complet.', zh: '创建一次，覆盖全球。12种界面语言。多语言配音。完整RTL支持。', pt: 'Crie uma vez, alcance o mundo. 12 idiomas de interface. Dublagem multilíngue. Suporte completo RTL.', es: 'Crea una vez, llega al mundo. 12 idiomas de interfaz. Doblaje multilingüe. Soporte RTL completo.', de: 'Einmal erstellen, die Welt erreichen. 12 Sprachen. Mehrsprachige Synchronisation. Volle RTL-Unterstützung.', it: 'Crea una volta, raggiungi il mondo. 12 lingue interfaccia. Doppiaggio multilingue. Supporto RTL completo.', ru: 'Создайте один раз — охватите весь мир. 12 языков интерфейса. Многоязычная озвучка. Полная поддержка RTL.', ko: '한 번 제작, 전 세계에 도달. 12개 인터페이스 언어. 다국어 더빙. 완전한 RTL 지원.', ja: '一度作成すれば世界中に届く。12のインターフェース言語。多言語吹き替え。完全なRTLサポート。' },
  'global.uiLangs': { en: '12 UI Languages', he: '12 שפות ממשק', ar: '12 لغة واجهة', fr: '12 langues d\'interface', zh: '12种界面语言', pt: '12 idiomas de interface', es: '12 idiomas de interfaz', de: '12 UI-Sprachen', it: '12 lingue interfaccia', ru: '12 языков интерфейса', ko: '12개 UI 언어', ja: '12のUI言語' },
  'global.dubbing': { en: 'Multi-Language Dubbing', he: 'דיבוב רב-לשוני', ar: 'دبلجة متعددة اللغات', fr: 'Doublage multilingue', zh: '多语言配音', pt: 'Dublagem multilíngue', es: 'Doblaje multilingüe', de: 'Mehrsprachige Synchronisation', it: 'Doppiaggio multilingue', ru: 'Многоязычная озвучка', ko: '다국어 더빙', ja: '多言語吹き替え' },
  'global.dubbingDesc': { en: 'Same film, different voices. Hebrew, English, Chinese, and more coming.', he: 'אותו סרט, קולות שונים. עברית, אנגלית, סינית, ועוד בדרך.', ar: 'نفس الفيلم، أصوات مختلفة. العبرية والإنجليزية والصينية والمزيد قادم.', fr: 'Même film, voix différentes. Hébreu, anglais, chinois, et plus à venir.', zh: '同一部电影，不同的配音。希伯来语、英语、中文，更多语言即将推出。', pt: 'Mesmo filme, vozes diferentes. Hebraico, inglês, chinês, e mais em breve.', es: 'Misma película, voces diferentes. Hebreo, inglés, chino, y más por venir.', de: 'Gleicher Film, verschiedene Stimmen. Hebräisch, Englisch, Chinesisch und mehr.', it: 'Stesso film, voci diverse. Ebraico, inglese, cinese e altro in arrivo.', ru: 'Тот же фильм, разные голоса. Иврит, английский, китайский и другие.', ko: '같은 영화, 다른 목소리. 히브리어, 영어, 중국어 등 추가 예정.', ja: '同じ映画、異なる声。ヘブライ語、英語、中国語、さらに追加予定。' },
  'global.rtl': { en: 'RTL Native', he: 'תמיכה מקורית ב-RTL', ar: 'دعم أصلي لـ RTL', fr: 'Support RTL natif', zh: 'RTL原生支持', pt: 'Suporte RTL nativo', es: 'Soporte RTL nativo', de: 'Nativer RTL-Support', it: 'Supporto RTL nativo', ru: 'Нативная поддержка RTL', ko: '네이티브 RTL 지원', ja: 'ネイティブRTLサポート' },
  'global.rtlDesc': { en: 'Perfect Hebrew and Arabic support, right out of the box.', he: 'תמיכה מושלמת בעברית וערבית, מהרגע הראשון.', ar: 'دعم مثالي للعربية والعبرية، جاهز للاستخدام فوراً.', fr: 'Support parfait de l\'hébreu et de l\'arabe, prêt à l\'emploi.', zh: '完美支持希伯来语和阿拉伯语，开箱即用。', pt: 'Suporte perfeito para hebraico e árabe, pronto para usar.', es: 'Soporte perfecto para hebreo y árabe, listo para usar.', de: 'Perfekte Hebräisch- und Arabisch-Unterstützung, sofort einsatzbereit.', it: 'Supporto perfetto per ebraico e arabo, pronto all\'uso.', ru: 'Идеальная поддержка иврита и арабского, из коробки.', ko: '히브리어와 아랍어를 완벽하게 지원, 바로 사용 가능.', ja: 'ヘブライ語とアラビア語の完璧なサポート。' },

  // ===== PRICING =====
  'pricing.title': { en: 'Simple, Transparent Pricing', he: 'תמחור פשוט ושקוף', ar: 'أسعار بسيطة وشفافة', fr: 'Tarification simple et transparente', zh: '简单透明的定价', pt: 'Preços simples e transparentes', es: 'Precios simples y transparentes', de: 'Einfache, transparente Preise', it: 'Prezzi semplici e trasparenti', ru: 'Простые и прозрачные цены', ko: '간단하고 투명한 요금제', ja: 'シンプルで透明な料金' },
  'pricing.sub': { en: 'Start free. Scale as you create.', he: 'התחל בחינם. גדל ככל שאתה יוצר.', ar: 'ابدأ مجاناً. توسّع مع إبداعك.', fr: 'Commencez gratuitement. Évoluez au fil de vos créations.', zh: '免费开始。随创作扩展。', pt: 'Comece grátis. Escale conforme você cria.', es: 'Empieza gratis. Escala según creas.', de: 'Starte kostenlos. Skaliere mit deiner Kreativität.', it: 'Inizia gratis. Scala man mano che crei.', ru: 'Начните бесплатно. Масштабируйтесь по мере создания.', ko: '무료로 시작. 창작하면서 확장.', ja: '無料で開始。作るほどスケールアップ。' },
  'pricing.popular': { en: 'Most Popular', he: 'הכי פופולרי', ar: 'الأكثر شعبية', fr: 'Le plus populaire', zh: '最受欢迎', pt: 'Mais popular', es: 'Más popular', de: 'Am beliebtesten', it: 'Più popolare', ru: 'Самый популярный', ko: '가장 인기', ja: '最も人気' },
  'pricing.perMonth': { en: '/month', he: '/חודש', ar: '/شهر', fr: '/mois', zh: '/月', pt: '/mês', es: '/mes', de: '/Monat', it: '/mese', ru: '/месяц', ko: '/월', ja: '/月' },
  'pricing.startFree': { en: 'Start Free', he: 'התחל בחינם', ar: 'ابدأ مجاناً', fr: 'Commencer gratuitement', zh: '免费开始', pt: 'Começar grátis', es: 'Empezar gratis', de: 'Kostenlos starten', it: 'Inizia gratis', ru: 'Начать бесплатно', ko: '무료 시작', ja: '無料で始める' },
  'pricing.getStarted': { en: 'Get Started', he: 'להתחיל', ar: 'ابدأ الآن', fr: 'Commencer', zh: '立即开始', pt: 'Começar', es: 'Comenzar', de: 'Loslegen', it: 'Inizia', ru: 'Начать', ko: '시작하기', ja: '始める' },

  // ===== FINAL CTA =====
  'cta.title': { en: 'Your First Scene\nIs On Us', he: 'הסצנה הראשונה\nעלינו', ar: 'مشهدك الأول\nعلينا', fr: 'Votre première scène\nest offerte', zh: '您的第一个场景\n由我们提供', pt: 'Sua primeira cena\né por nossa conta', es: 'Tu primera escena\ncorre por nuestra cuenta', de: 'Deine erste Szene\ngeht auf uns', it: 'La tua prima scena\nè offerta da noi', ru: 'Ваша первая сцена\nза наш счёт', ko: '첫 번째 장면은\n무료입니다', ja: '最初のシーンは\n無料です' },
  'cta.sub': { en: 'No credit card. No commitment. Just paste your story and press play.', he: 'בלי כרטיס אשראי. בלי התחייבות. פשוט הדבק סיפור ולחץ Play.', ar: 'بدون بطاقة ائتمان. بدون التزام. فقط الصق قصتك واضغط تشغيل.', fr: 'Pas de carte bancaire. Pas d\'engagement. Collez votre histoire et appuyez sur lecture.', zh: '无需信用卡。无需承诺。粘贴故事，点击播放。', pt: 'Sem cartão de crédito. Sem compromisso. Cole sua história e pressione play.', es: 'Sin tarjeta de crédito. Sin compromiso. Pega tu historia y presiona play.', de: 'Keine Kreditkarte. Keine Verpflichtung. Geschichte einfügen und abspielen.', it: 'Nessuna carta di credito. Nessun impegno. Incolla la tua storia e premi play.', ru: 'Без кредитной карты. Без обязательств. Вставьте историю и нажмите «Воспроизвести».', ko: '신용카드 필요 없음. 약정 없음. 이야기를 붙여넣고 재생을 누르세요.', ja: 'クレジットカード不要。契約不要。ストーリーを貼り付けて再生するだけ。' },

  // ===== HERO STATS =====
  'hero.trusted': { en: 'Trusted by creators worldwide', he: 'יוצרים מהעולם סומכים עלינו', ar: 'موثوق من المبدعين حول العالم', fr: 'Approuvé par des créateurs du monde entier', zh: '全球创作者信赖', pt: 'Confiado por criadores do mundo todo', es: 'Confiado por creadores de todo el mundo', de: 'Von Kreativen weltweit vertraut', it: 'Affidato da creatori di tutto il mondo', ru: 'Доверие создателей по всему миру', ko: '전 세계 크리에이터의 신뢰', ja: '世界中のクリエイターに信頼されています' },
  'hero.stats': { en: '10,000+ Scenes Created \u2022 500+ Films Produced \u2022 50+ Countries', he: '10,000+ סצנות נוצרו \u2022 500+ סרטים הופקו \u2022 50+ מדינות', ar: '10,000+ مشهد تم إنشاؤه \u2022 500+ فيلم تم إنتاجه \u2022 50+ دولة', fr: '10 000+ scènes créées \u2022 500+ films produits \u2022 50+ pays', zh: '10,000+ 场景已创建 \u2022 500+ 部电影已制作 \u2022 50+ 个国家', pt: '10.000+ cenas criadas \u2022 500+ filmes produzidos \u2022 50+ países', es: '10.000+ escenas creadas \u2022 500+ películas producidas \u2022 50+ países', de: '10.000+ Szenen erstellt \u2022 500+ Filme produziert \u2022 50+ Länder', it: '10.000+ scene create \u2022 500+ film prodotti \u2022 50+ paesi', ru: '10 000+ сцен создано \u2022 500+ фильмов произведено \u2022 50+ стран', ko: '10,000+ 장면 생성 \u2022 500+ 영화 제작 \u2022 50+ 국가', ja: '10,000+ シーン作成 \u2022 500+ 映画制作 \u2022 50+ か国' },

  // ===== HOW SHOWCASE =====
  'how.showcase.title': { en: 'From Text to Cinema', he: 'מטקסט לקולנוע', ar: 'من النص إلى السينما', fr: 'Du texte au cinéma', zh: '从文字到电影', pt: 'Do texto ao cinema', es: 'Del texto al cine', de: 'Vom Text zum Kino', it: 'Dal testo al cinema', ru: 'От текста к кино', ko: '텍스트에서 영화로', ja: 'テキストから映画へ' },
  'how.showcase.text': { en: '"A tiny crack appeared in the massive egg. Viscous fluid oozed through as the baby Velociraptor pushed its snout into the prehistoric dawn, scales glistening wet under the ancient jungle canopy..."', he: '"סדק זעיר הופיע בביצה הענקית. נוזל צמיגי חלחל החוצה בעוד גור הוולוצירפטור דוחף את לועו לתוך שחר פרהיסטורי, קשקשיו נוצצים רטובים מתחת לחופת הג\'ונגל הקדום..."', ar: '"ظهر شق صغير في البيضة الضخمة. تسرب سائل لزج بينما دفع صغير الفيلوسيرابتور أنفه نحو فجر ما قبل التاريخ، حراشفه تلمع مبللة تحت مظلة الغابة القديمة..."', fr: '"Une minuscule fissure apparut sur l\'œuf massif. Un fluide visqueux suinta tandis que le bébé Vélociraptor poussait son museau dans l\'aube préhistorique..."', zh: '"巨蛋上出现了一道细小的裂缝。粘稠的液体渗出，小迅猛龙将鼻子推入史前的黎明，鳞片在古老的丛林树冠下闪闪发光..."', pt: '"Uma pequena rachadura apareceu no ovo massivo. Fluido viscoso escorreu enquanto o bebê Velociraptor empurrava seu focinho para o amanhecer pré-histórico..."', es: '"Una pequeña grieta apareció en el huevo masivo. Un fluido viscoso se filtró mientras el bebé Velociraptor empujaba su hocico hacia el amanecer prehistórico..."', de: '"Ein winziger Riss erschien am massiven Ei. Zähflüssige Flüssigkeit sickerte heraus, während der Baby-Velociraptor seine Schnauze in die prähistorische Morgendämmerung schob..."', it: '"Una piccola crepa apparve sull\'enorme uovo. Un fluido viscoso colò fuori mentre il piccolo Velociraptor spingeva il muso nell\'alba preistorica..."', ru: '"На огромном яйце появилась крошечная трещина. Вязкая жидкость просочилась наружу, пока детёныш велоцираптора проталкивал мордочку в доисторический рассвет..."', ko: '"거대한 알에 작은 금이 갔다. 끈적한 액체가 스며나오며 아기 벨로시랩터가 선사시대의 새벽 속으로 주둥이를 밀어넣었다..."', ja: '"巨大な卵に小さな亀裂が現れた。粘性のある液体が滲み出し、赤ちゃんヴェロキラプトルが先史時代の夜明けへと鼻先を押し出した..."' },

  // ===== GALLERY =====
  'gallery.title': { en: 'Created with Cinema AI Studio', he: 'נוצר עם Cinema AI Studio', ar: 'تم إنشاؤه باستخدام Cinema AI Studio', fr: 'Créé avec Cinema AI Studio', zh: '使用 Cinema AI Studio 创作', pt: 'Criado com Cinema AI Studio', es: 'Creado con Cinema AI Studio', de: 'Erstellt mit Cinema AI Studio', it: 'Creato con Cinema AI Studio', ru: 'Создано с Cinema AI Studio', ko: 'Cinema AI Studio로 제작', ja: 'Cinema AI Studioで制作' },
  'gallery.sub': { en: 'Every image you see was generated by AI — imagine what your stories will look like', he: 'כל תמונה שאתה רואה נוצרה על ידי AI — דמיין איך הסיפורים שלך ייראו', ar: 'كل صورة تراها تم إنشاؤها بالذكاء الاصطناعي — تخيل كيف ستبدو قصصك', fr: 'Chaque image a été générée par l\'IA — imaginez vos histoires', zh: '每张图片都由AI生成——想象您的故事会是什么样子', pt: 'Cada imagem foi gerada por IA — imagine como suas histórias ficarão', es: 'Cada imagen fue generada por IA — imagina cómo se verán tus historias', de: 'Jedes Bild wurde von KI erstellt — stell dir vor, wie deine Geschichten aussehen', it: 'Ogni immagine è stata generata dall\'IA — immagina come appariranno le tue storie', ru: 'Каждое изображение создано ИИ — представьте, как будут выглядеть ваши истории', ko: '모든 이미지는 AI가 생성했습니다 — 당신의 이야기가 어떻게 보일지 상상해보세요', ja: 'すべての画像はAIが生成 — あなたの物語がどう見えるか想像してみてください' },

  // ===== FOOTER =====
  'footer.product': { en: 'Product', he: 'מוצר', ar: 'المنتج', fr: 'Produit', zh: '产品', pt: 'Produto', es: 'Producto', de: 'Produkt', it: 'Prodotto', ru: 'Продукт', ko: '제품', ja: '製品' },
  'footer.company': { en: 'Company', he: 'חברה', ar: 'الشركة', fr: 'Entreprise', zh: '公司', pt: 'Empresa', es: 'Empresa', de: 'Unternehmen', it: 'Azienda', ru: 'Компания', ko: '회사', ja: '会社' },
  'footer.features': { en: 'Features', he: 'תכונות', ar: 'الميزات', fr: 'Fonctionnalités', zh: '功能', pt: 'Recursos', es: 'Características', de: 'Funktionen', it: 'Funzionalità', ru: 'Возможности', ko: '기능', ja: '機能' },
  'footer.about': { en: 'About', he: 'אודות', ar: 'حول', fr: 'À propos', zh: '关于', pt: 'Sobre', es: 'Acerca de', de: 'Über uns', it: 'Chi siamo', ru: 'О нас', ko: '소개', ja: '概要' },
  'footer.contact': { en: 'Contact', he: 'צור קשר', ar: 'اتصل بنا', fr: 'Contact', zh: '联系', pt: 'Contato', es: 'Contacto', de: 'Kontakt', it: 'Contatto', ru: 'Контакты', ko: '연락처', ja: 'お問い合わせ' },
  'footer.terms': { en: 'Terms', he: 'תנאים', ar: 'الشروط', fr: 'Conditions', zh: '条款', pt: 'Termos', es: 'Términos', de: 'AGB', it: 'Termini', ru: 'Условия', ko: '약관', ja: '利用規約' },
  'footer.privacy': { en: 'Privacy', he: 'פרטיות', ar: 'الخصوصية', fr: 'Confidentialité', zh: '隐私', pt: 'Privacidade', es: 'Privacidad', de: 'Datenschutz', it: 'Privacy', ru: 'Конфиденциальность', ko: '개인정보', ja: 'プライバシー' },
  'footer.rights': { en: 'All rights reserved.', he: 'כל הזכויות שמורות.', ar: 'جميع الحقوق محفوظة.', fr: 'Tous droits réservés.', zh: '版权所有。', pt: 'Todos os direitos reservados.', es: 'Todos los derechos reservados.', de: 'Alle Rechte vorbehalten.', it: 'Tutti i diritti riservati.', ru: 'Все права защищены.', ko: '모든 권리 보유.', ja: '全著作権所有。' },
};

export function tLanding(key: string, lang: UILanguage): string {
  const entry = T[key];
  if (!entry) return key;
  return entry[lang] || entry.en || key;
}
