import { UILanguage } from './types';

export const UI_LANGUAGES: { code: UILanguage; label: string; flag: string; dir: 'ltr' | 'rtl' }[] = [
  { code: 'en', label: 'English', flag: '🇺🇸', dir: 'ltr' },
  { code: 'he', label: 'עברית', flag: '🇮🇱', dir: 'rtl' },
  { code: 'ar', label: 'العربية', flag: '🇸🇦', dir: 'rtl' },
  { code: 'fr', label: 'Français', flag: '🇫🇷', dir: 'ltr' },
  { code: 'zh', label: '中文', flag: '🇨🇳', dir: 'ltr' },
  { code: 'pt', label: 'Português', flag: '🇧🇷', dir: 'ltr' },
  { code: 'es', label: 'Español', flag: '🇪🇸', dir: 'ltr' },
  { code: 'de', label: 'Deutsch', flag: '🇩🇪', dir: 'ltr' },
  { code: 'it', label: 'Italiano', flag: '🇮🇹', dir: 'ltr' },
  { code: 'ru', label: 'Русский', flag: '🇷🇺', dir: 'ltr' },
  { code: 'ko', label: '한국어', flag: '🇰🇷', dir: 'ltr' },
  { code: 'ja', label: '日本語', flag: '🇯🇵', dir: 'ltr' },
];

// All translatable strings keyed by a flat camelCase key
const translations: Record<string, Record<UILanguage, string>> = {
  // ===== NAV =====
  navProjects:     { en: 'Projects', he: 'פרויקטים', ar: 'المشاريع', fr: 'Projets', zh: '项目', pt: 'Projetos', es: 'Proyectos', de: 'Projekte', it: 'Progetti', ru: 'Проекты', ko: '프로젝트', ja: 'プロジェクト' },
  navStory:        { en: 'Story', he: 'סיפור', ar: 'القصة', fr: 'Histoire', zh: '故事', pt: 'História', es: 'Historia', de: 'Geschichte', it: 'Storia', ru: 'Сюжет', ko: '스토리', ja: 'ストーリー' },
  navStyle:        { en: 'Style', he: 'סגנון', ar: 'الأسلوب', fr: 'Style', zh: '风格', pt: 'Estilo', es: 'Estilo', de: 'Stil', it: 'Stile', ru: 'Стиль', ko: '스타일', ja: 'スタイル' },
  navLanguage:     { en: 'Language', he: 'שפה', ar: 'اللغة', fr: 'Langue', zh: '语言', pt: 'Idioma', es: 'Idioma', de: 'Sprache', it: 'Lingua', ru: 'Язык', ko: '언어', ja: '言語' },
  navTimeline:     { en: 'Timeline', he: 'ציר זמן', ar: 'الجدول الزمني', fr: 'Chronologie', zh: '时间轴', pt: 'Linha do tempo', es: 'Línea de tiempo', de: 'Zeitleiste', it: 'Timeline', ru: 'Таймлайн', ko: '타임라인', ja: 'タイムライン' },
  navPreview:      { en: 'Preview', he: 'תצוגה מקדימה', ar: 'معاينة', fr: 'Aperçu', zh: '预览', pt: 'Pré-visualização', es: 'Vista previa', de: 'Vorschau', it: 'Anteprima', ru: 'Просмотр', ko: '미리보기', ja: 'プレビュー' },
  navPricing:      { en: 'Pricing', he: 'מחירים', ar: 'الأسعار', fr: 'Tarifs', zh: '定价', pt: 'Preços', es: 'Precios', de: 'Preise', it: 'Prezzi', ru: 'Цены', ko: '요금', ja: '料金' },

  // ===== HEADER =====
  appTitle:        { en: 'Cinematic Studio', he: 'סטודיו קולנועי', ar: 'استوديو سينمائي', fr: 'Studio Cinématique', zh: '电影工作室', pt: 'Estúdio Cinematográfico', es: 'Estudio Cinematográfico', de: 'Filmstudio', it: 'Studio Cinematografico', ru: 'Киностудия', ko: '시네마틱 스튜디오', ja: 'シネマティックスタジオ' },
  estimatedCost:   { en: 'Session cost', he: 'עלות הפעלה', ar: 'تكلفة الجلسة', fr: 'Coût de session', zh: '会话费用', pt: 'Custo da sessão', es: 'Costo de sesión', de: 'Sitzungskosten', it: 'Costo sessione', ru: 'Стоимость сеанса', ko: '세션 비용', ja: 'セッションコスト' },
  viewPlans:       { en: 'View plans', he: 'תוכניות', ar: 'عرض الخطط', fr: 'Voir les plans', zh: '查看计划', pt: 'Ver planos', es: 'Ver planes', de: 'Pläne ansehen', it: 'Vedi piani', ru: 'Тарифы', ko: '요금제 보기', ja: 'プランを見る' },
  setApiKey:       { en: 'Set API Key', he: 'הגדר מפתח API', ar: 'تعيين مفتاح API', fr: 'Clé API', zh: '设置API密钥', pt: 'Definir chave API', es: 'Configurar clave API', de: 'API-Schlüssel', it: 'Imposta chiave API', ru: 'API-ключ', ko: 'API 키 설정', ja: 'APIキー設定' },
  connect:         { en: 'Connect', he: 'חבר', ar: 'اتصال', fr: 'Connecter', zh: '连接', pt: 'Conectar', es: 'Conectar', de: 'Verbinden', it: 'Connetti', ru: 'Подключить', ko: '연결', ja: '接続' },
  key:             { en: 'Key', he: 'מפתח', ar: 'مفتاح', fr: 'Clé', zh: '密钥', pt: 'Chave', es: 'Clave', de: 'Schlüssel', it: 'Chiave', ru: 'Ключ', ko: '키', ja: 'キー' },
  scenesLeft:      { en: 'scenes left', he: 'סצנות נותרו', ar: 'مشاهد متبقية', fr: 'scènes restantes', zh: '剩余场景', pt: 'cenas restantes', es: 'escenas restantes', de: 'Szenen übrig', it: 'scene rimanenti', ru: 'сцен осталось', ko: '남은 장면', ja: '残りシーン' },
  filmsLeft:       { en: 'films left', he: 'סרטים נותרו', ar: 'أفلام متبقية', fr: 'films restants', zh: '剩余影片', pt: 'filmes restantes', es: 'películas restantes', de: 'Filme übrig', it: 'film rimanenti', ru: 'фильмов осталось', ko: '남은 영화', ja: '残り映画' },

  // ===== API KEY DIALOG =====
  apiKeyTitle:     { en: 'API Key', he: 'מפתח API', ar: 'مفتاح API', fr: 'Clé API', zh: 'API密钥', pt: 'Chave API', es: 'Clave API', de: 'API-Schlüssel', it: 'Chiave API', ru: 'API-ключ', ko: 'API 키', ja: 'APIキー' },
  getApiKey:       { en: 'Get your free API key', he: 'קבל מפתח API חינם', ar: 'احصل على مفتاح API مجاني', fr: 'Obtenez votre clé API gratuite', zh: '获取免费API密钥', pt: 'Obtenha sua chave API gratuita', es: 'Obtén tu clave API gratuita', de: 'Kostenlosen API-Schlüssel erhalten', it: 'Ottieni la tua chiave API gratuita', ru: 'Получите бесплатный API-ключ', ko: '무료 API 키 받기', ja: '無料APIキーを取得' },
  activeKey:       { en: 'Active key', he: 'מפתח פעיל', ar: 'مفتاح نشط', fr: 'Clé active', zh: '活跃密钥', pt: 'Chave ativa', es: 'Clave activa', de: 'Aktiver Schlüssel', it: 'Chiave attiva', ru: 'Активный ключ', ko: '활성 키', ja: 'アクティブキー' },
  invalidApiKey:   { en: 'Invalid API key — only English letters, numbers, dashes and underscores.', he: 'מפתח API לא תקין — רק אותיות אנגליות, מספרים, מקפים וקווים תחתונים.', ar: 'مفتاح API غير صالح — فقط أحرف إنجليزية وأرقام وشرطات وشرطات سفلية.', fr: 'Clé API invalide — uniquement lettres, chiffres, tirets et underscores.', zh: '无效的API密钥 — 仅允许英文字母、数字、破折号和下划线。', pt: 'Chave API inválida — apenas letras, números, hifens e sublinhados.', es: 'Clave API inválida — solo letras, números, guiones y guiones bajos.', de: 'Ungültiger API-Schlüssel — nur Buchstaben, Zahlen, Bindestriche und Unterstriche.', it: 'Chiave API non valida — solo lettere, numeri, trattini e underscore.', ru: 'Неверный API-ключ — только буквы, цифры, дефисы и подчёркивания.', ko: '잘못된 API 키 — 영문자, 숫자, 대시, 밑줄만 허용됩니다.', ja: '無効なAPIキー — 英字、数字、ハイフン、アンダースコアのみ。' },
  save:            { en: 'Save', he: 'שמור', ar: 'حفظ', fr: 'Enregistrer', zh: '保存', pt: 'Salvar', es: 'Guardar', de: 'Speichern', it: 'Salva', ru: 'Сохранить', ko: '저장', ja: '保存' },
  remove:          { en: 'Remove', he: 'הסר', ar: 'إزالة', fr: 'Supprimer', zh: '删除', pt: 'Remover', es: 'Eliminar', de: 'Entfernen', it: 'Rimuovi', ru: 'Удалить', ko: '삭제', ja: '削除' },

  // ===== PROFILE MODAL =====
  profileTitle:    { en: 'Profile', he: 'פרופיל', ar: 'الملف الشخصي', fr: 'Profil', zh: '个人资料', pt: 'Perfil', es: 'Perfil', de: 'Profil', it: 'Profilo', ru: 'Профиль', ko: '프로필', ja: 'プロフィール' },
  nameLabel:       { en: 'Name', he: 'שם', ar: 'الاسم', fr: 'Nom', zh: '姓名', pt: 'Nome', es: 'Nombre', de: 'Name', it: 'Nome', ru: 'Имя', ko: '이름', ja: '名前' },
  yourName:        { en: 'Your name', he: 'השם שלך', ar: 'اسمك', fr: 'Votre nom', zh: '您的姓名', pt: 'Seu nome', es: 'Tu nombre', de: 'Ihr Name', it: 'Il tuo nome', ru: 'Ваше имя', ko: '이름 입력', ja: 'お名前' },
  emailLabel:      { en: 'Email', he: 'אימייל', ar: 'البريد الإلكتروني', fr: 'E-mail', zh: '电子邮件', pt: 'E-mail', es: 'Correo', de: 'E-Mail', it: 'Email', ru: 'Эл. почта', ko: '이메일', ja: 'メール' },
  currentPlan:     { en: 'Current Plan', he: 'תוכנית נוכחית', ar: 'الخطة الحالية', fr: 'Plan actuel', zh: '当前计划', pt: 'Plano atual', es: 'Plan actual', de: 'Aktueller Plan', it: 'Piano attuale', ru: 'Текущий план', ko: '현재 요금제', ja: '現在のプラン' },
  scenesUsed:      { en: 'Scenes used', he: 'סצנות שנוצרו', ar: 'المشاهد المستخدمة', fr: 'Scènes utilisées', zh: '已使用场景', pt: 'Cenas usadas', es: 'Escenas usadas', de: 'Szenen verwendet', it: 'Scene usate', ru: 'Использовано сцен', ko: '사용한 장면', ja: '使用シーン' },
  changePlan:      { en: 'Change Plan', he: 'החלף תוכנית', ar: 'تغيير الخطة', fr: 'Changer de plan', zh: '更换计划', pt: 'Alterar plano', es: 'Cambiar plan', de: 'Plan ändern', it: 'Cambia piano', ru: 'Сменить план', ko: '요금제 변경', ja: 'プラン変更' },

  // ===== LAST FRAME MODAL =====
  lastFrameTitle:  { en: 'Last Frame — Starting Point for Next Scene', he: 'פריים אחרון — נקודת ההתחלה לסצנה הבאה', ar: 'الإطار الأخير — نقطة البداية للمشهد التالي', fr: 'Dernière image — Point de départ de la scène suivante', zh: '最后一帧 — 下一场景的起点', pt: 'Último frame — Ponto de partida para a próxima cena', es: 'Último fotograma — Punto de inicio para la siguiente escena', de: 'Letztes Bild — Startpunkt für die nächste Szene', it: 'Ultimo fotogramma — Punto di partenza per la scena successiva', ru: 'Последний кадр — Начальная точка следующей сцены', ko: '마지막 프레임 — 다음 장면 시작점', ja: '最終フレーム — 次のシーンの開始点' },
  chooseHowStart:  { en: 'Choose how the next scene should start:', he: 'בחר איך הסצנה הבאה תתחיל:', ar: 'اختر كيف يبدأ المشهد التالي:', fr: 'Choisissez comment la scène suivante doit commencer :', zh: '选择下一场景的开始方式：', pt: 'Escolha como a próxima cena deve começar:', es: 'Elige cómo debe comenzar la siguiente escena:', de: 'Wählen Sie, wie die nächste Szene beginnen soll:', it: 'Scegli come deve iniziare la scena successiva:', ru: 'Выберите, как должна начаться следующая сцена:', ko: '다음 장면의 시작 방법을 선택하세요:', ja: '次のシーンの開始方法を選択してください：' },
  continueFrame:   { en: 'Continue from this frame', he: 'המשך מהפריים הזה', ar: 'استمر من هذا الإطار', fr: 'Continuer depuis cette image', zh: '从此帧继续', pt: 'Continuar deste frame', es: 'Continuar desde este fotograma', de: 'Von diesem Bild fortfahren', it: 'Continua da questo fotogramma', ru: 'Продолжить с этого кадра', ko: '이 프레임에서 계속', ja: 'このフレームから続行' },
  seamlessTransition: { en: 'Seamless transition', he: 'מעבר חלק', ar: 'انتقال سلس', fr: 'Transition fluide', zh: '无缝过渡', pt: 'Transição suave', es: 'Transición fluida', de: 'Nahtloser Übergang', it: 'Transizione fluida', ru: 'Плавный переход', ko: '매끄러운 전환', ja: 'シームレスな移行' },
  freshScene:      { en: 'Fresh scene', he: 'סצנה חדשה', ar: 'مشهد جديد', fr: 'Nouvelle scène', zh: '全新场景', pt: 'Nova cena', es: 'Nueva escena', de: 'Neue Szene', it: 'Nuova scena', ru: 'Новая сцена', ko: '새 장면', ja: '新しいシーン' },
  newAngle:        { en: 'New angle / location', he: 'זווית / מיקום חדש', ar: 'زاوية / موقع جديد', fr: 'Nouvel angle / lieu', zh: '新角度/位置', pt: 'Novo ângulo / local', es: 'Nuevo ángulo / ubicación', de: 'Neuer Winkel / Ort', it: 'Nuova angolazione / luogo', ru: 'Новый ракурс / место', ko: '새 각도 / 위치', ja: '新しいアングル / 場所' },
  cancel:          { en: 'Cancel', he: 'ביטול', ar: 'إلغاء', fr: 'Annuler', zh: '取消', pt: 'Cancelar', es: 'Cancelar', de: 'Abbrechen', it: 'Annulla', ru: 'Отмена', ko: '취소', ja: 'キャンセル' },

  // ===== PROJECTS =====
  yourProjects:    { en: 'Your Projects', he: 'הפרויקטים שלך', ar: 'مشاريعك', fr: 'Vos projets', zh: '您的项目', pt: 'Seus projetos', es: 'Tus proyectos', de: 'Ihre Projekte', it: 'I tuoi progetti', ru: 'Ваши проекты', ko: '내 프로젝트', ja: 'あなたのプロジェクト' },
  continueOrStart: { en: 'Continue a previous project or start a new one', he: 'המשך פרויקט קודם או התחל חדש', ar: 'أكمل مشروعًا سابقًا أو ابدأ جديدًا', fr: 'Continuez un projet ou commencez-en un nouveau', zh: '继续之前的项目或开始新项目', pt: 'Continue um projeto anterior ou inicie um novo', es: 'Continúa un proyecto anterior o inicia uno nuevo', de: 'Setzen Sie ein Projekt fort oder starten Sie ein neues', it: 'Continua un progetto precedente o iniziane uno nuovo', ru: 'Продолжите проект или начните новый', ko: '이전 프로젝트를 계속하거나 새로 시작하세요', ja: '前のプロジェクトを続けるか、新しく始めましょう' },
  newProject:      { en: 'New Project', he: 'פרויקט חדש', ar: 'مشروع جديد', fr: 'Nouveau projet', zh: '新项目', pt: 'Novo projeto', es: 'Nuevo proyecto', de: 'Neues Projekt', it: 'Nuovo progetto', ru: 'Новый проект', ko: '새 프로젝트', ja: '新しいプロジェクト' },
  noSavedProjects: { en: 'No saved projects', he: 'אין פרויקטים שמורים', ar: 'لا توجد مشاريع محفوظة', fr: 'Aucun projet sauvegardé', zh: '没有保存的项目', pt: 'Nenhum projeto salvo', es: 'Sin proyectos guardados', de: 'Keine gespeicherten Projekte', it: 'Nessun progetto salvato', ru: 'Нет сохранённых проектов', ko: '저장된 프로젝트 없음', ja: '保存されたプロジェクトなし' },
  createFirstProject: { en: 'Create your first movie project above', he: 'צור את פרויקט הסרט הראשון שלך', ar: 'أنشئ مشروع فيلمك الأول أعلاه', fr: 'Créez votre premier projet ci-dessus', zh: '在上方创建您的第一个电影项目', pt: 'Crie seu primeiro projeto de filme acima', es: 'Crea tu primer proyecto de película arriba', de: 'Erstellen Sie Ihr erstes Filmprojekt oben', it: 'Crea il tuo primo progetto sopra', ru: 'Создайте свой первый проект выше', ko: '위에서 첫 번째 영화 프로젝트를 만드세요', ja: '上で最初の映画プロジェクトを作成してください' },
  continueBtn:     { en: 'Continue', he: 'המשך', ar: 'متابعة', fr: 'Continuer', zh: '继续', pt: 'Continuar', es: 'Continuar', de: 'Fortsetzen', it: 'Continua', ru: 'Продолжить', ko: '계속', ja: '続ける' },
  scenes:          { en: 'scenes', he: 'סצנות', ar: 'مشاهد', fr: 'scènes', zh: '场景', pt: 'cenas', es: 'escenas', de: 'Szenen', it: 'scene', ru: 'сцен', ko: '장면', ja: 'シーン' },

  // ===== STORY STEP =====
  tellStory:       { en: 'Tell your story', he: 'ספר את הסיפור שלך', ar: 'أخبر قصتك', fr: 'Racontez votre histoire', zh: '讲述你的故事', pt: 'Conte sua história', es: 'Cuenta tu historia', de: 'Erzählen Sie Ihre Geschichte', it: 'Racconta la tua storia', ru: 'Расскажите свою историю', ko: '당신의 이야기를 들려주세요', ja: 'あなたの物語を聞かせてください' },
  styleLabel:      { en: 'Style:', he: 'סגנון:', ar: 'الأسلوب:', fr: 'Style :', zh: '风格：', pt: 'Estilo:', es: 'Estilo:', de: 'Stil:', it: 'Stile:', ru: 'Стиль:', ko: '스타일:', ja: 'スタイル：' },
  inputLabel:      { en: 'Input:', he: 'קלט:', ar: 'المدخل:', fr: 'Entrée :', zh: '输入：', pt: 'Entrada:', es: 'Entrada:', de: 'Eingabe:', it: 'Input:', ru: 'Ввод:', ko: '입력:', ja: '入力：' },
  modelLabel:      { en: 'Model:', he: 'מודל:', ar: 'النموذج:', fr: 'Modèle :', zh: '模型：', pt: 'Modelo:', es: 'Modelo:', de: 'Modell:', it: 'Modello:', ru: 'Модель:', ko: '모델:', ja: 'モデル：' },
  movieLength:     { en: 'Movie Length', he: 'אורך הסרט', ar: 'مدة الفيلم', fr: 'Durée du film', zh: '电影长度', pt: 'Duração do filme', es: 'Duración de la película', de: 'Filmlänge', it: 'Durata del film', ru: 'Длина фильма', ko: '영화 길이', ja: '映画の長さ' },
  pasteScript:     { en: 'Paste your full script or book excerpt here...', he: 'הדבק כאן את הסקריפט או קטע מהספר...', ar: 'الصق النص الكامل أو مقتطف الكتاب هنا...', fr: 'Collez votre script ou extrait de livre ici...', zh: '在此粘贴您的完整剧本或书籍摘录...', pt: 'Cole seu roteiro completo ou trecho do livro aqui...', es: 'Pega tu guión completo o extracto del libro aquí...', de: 'Fügen Sie Ihr Skript oder Buchauszug hier ein...', it: 'Incolla il tuo copione o estratto del libro qui...', ru: 'Вставьте сюда ваш сценарий или отрывок из книги...', ko: '전체 스크립트 또는 책 발췌문을 여기에 붙여넣으세요...', ja: 'ここに台本や書籍の抜粋を貼り付けてください...' },
  describeIdea:    { en: 'Describe your movie idea...', he: 'תאר את רעיון הסרט...', ar: 'صف فكرة فيلمك...', fr: 'Décrivez votre idée de film...', zh: '描述您的电影创意...', pt: 'Descreva sua ideia de filme...', es: 'Describe tu idea de película...', de: 'Beschreiben Sie Ihre Filmidee...', it: 'Descrivi la tua idea per il film...', ru: 'Опишите свою идею фильма...', ko: '영화 아이디어를 설명하세요...', ja: '映画のアイデアを説明してください...' },
  creativeMode:    { en: 'Creative — AI enriches with cinematic depth', he: 'יצירתי — AI מעשיר בעומק קולנועי', ar: 'إبداعي — الذكاء الاصطناعي يثري بعمق سينمائي', fr: 'Créatif — L\'IA enrichit de profondeur cinématique', zh: '创意模式 — AI增添电影深度', pt: 'Criativo — IA enriquece com profundidade cinematográfica', es: 'Creativo — IA enriquece con profundidad cinematográfica', de: 'Kreativ — KI bereichert mit filmischer Tiefe', it: 'Creativo — L\'IA arricchisce con profondità cinematografica', ru: 'Творческий — ИИ обогащает кинематографической глубиной', ko: '크리에이티브 — AI가 영화적 깊이를 더합니다', ja: 'クリエイティブ — AIが映画的な深みを加えます' },
  strictMode:      { en: 'Strict — follows your text word for word', he: 'מדויק — עוקב אחרי הטקסט מילה במילה', ar: 'دقيق — يتبع النص كلمة بكلمة', fr: 'Strict — suit votre texte mot à mot', zh: '严格模式 — 逐字遵循您的文本', pt: 'Estrito — segue seu texto palavra por palavra', es: 'Estricto — sigue tu texto palabra por palabra', de: 'Strikt — folgt Ihrem Text wortgetreu', it: 'Rigoroso — segue il testo parola per parola', ru: 'Точный — следует тексту дословно', ko: '엄격 — 텍스트를 그대로 따릅니다', ja: '厳密 — テキストに忠実に従います' },
  aiMode:          { en: 'AI Script — AI writes scenes from your prompt', he: 'סקריפט AI — הAI כותב סצנות מהתיאור שלך', ar: 'نص AI — الذكاء الاصطناعي يكتب المشاهد من وصفك', fr: 'Script IA — L\'IA écrit les scènes', zh: 'AI剧本 — AI从你的描述编写场景', pt: 'Roteiro IA — IA escreve cenas do seu prompt', es: 'Guión IA — IA escribe escenas desde tu descripción', de: 'KI-Skript — KI schreibt Szenen aus Ihrer Beschreibung', it: 'Script IA — L\'IA scrive scene dal tuo prompt', ru: 'ИИ-сценарий — ИИ пишет сцены по вашему описанию', ko: 'AI 대본 — AI가 프롬프트에서 장면을 작성합니다', ja: 'AIスクリプト — AIがプロンプトからシーンを書きます' },
  manualMode:      { en: 'Manual — you write each scene yourself', he: 'ידני — אתה כותב כל סצנה בעצמך', ar: 'يدوي — أنت تكتب كل مشهد بنفسك', fr: 'Manuel — vous écrivez chaque scène', zh: '手动模式 — 你自己编写每个场景', pt: 'Manual — você escreve cada cena', es: 'Manual — tú escribes cada escena', de: 'Manuell — Sie schreiben jede Szene selbst', it: 'Manuale — scrivi ogni scena tu stesso', ru: 'Ручной — вы пишете каждую сцену сами', ko: '수동 — 각 장면을 직접 작성합니다', ja: '手動 — 各シーンを自分で書きます' },
  generateScript:  { en: 'Generate Script', he: 'צור סקריפט', ar: 'إنشاء السيناريو', fr: 'Générer le script', zh: '生成剧本', pt: 'Gerar roteiro', es: 'Generar guión', de: 'Skript generieren', it: 'Genera copione', ru: 'Создать сценарий', ko: '대본 생성', ja: 'スクリプト生成' },
  wordCount:       { en: 'words', he: 'מילים', ar: 'كلمات', fr: 'mots', zh: '字', pt: 'palavras', es: 'palabras', de: 'Wörter', it: 'parole', ru: 'слов', ko: '단어', ja: '語' },
  estScenes:       { en: 'est. scenes', he: 'סצנות משוערות', ar: 'مشاهد تقريبية', fr: 'scènes estimées', zh: '预计场景', pt: 'cenas estimadas', es: 'escenas estimadas', de: 'geschätzte Szenen', it: 'scene stimate', ru: 'примерно сцен', ko: '예상 장면', ja: '推定シーン' },
  estCost:         { en: 'est. cost', he: 'עלות משוערת', ar: 'التكلفة التقريبية', fr: 'coût estimé', zh: '预计成本', pt: 'custo estimado', es: 'costo estimado', de: 'geschätzte Kosten', it: 'costo stimato', ru: 'примерная стоимость', ko: '예상 비용', ja: '推定コスト' },

  // ===== MOVIE LENGTH =====
  shortLabel:      { en: 'Short', he: 'קצר', ar: 'قصير', fr: 'Court', zh: '短片', pt: 'Curto', es: 'Corto', de: 'Kurz', it: 'Corto', ru: 'Короткий', ko: '짧은', ja: '短い' },
  shortDesc:       { en: 'Condensed — key events only', he: 'תמצית — רק אירועים מרכזיים', ar: 'مختصر — الأحداث الرئيسية فقط', fr: 'Condensé — événements clés uniquement', zh: '精简 — 仅关键事件', pt: 'Condensado — apenas eventos-chave', es: 'Condensado — solo eventos clave', de: 'Verdichtet — nur Schlüsselereignisse', it: 'Condensato — solo eventi chiave', ru: 'Сжатый — только ключевые события', ko: '요약 — 핵심 사건만', ja: '凝縮 — 主要イベントのみ' },
  mediumLabel:     { en: 'Medium', he: 'בינוני', ar: 'متوسط', fr: 'Moyen', zh: '中等', pt: 'Médio', es: 'Medio', de: 'Mittel', it: 'Medio', ru: 'Средний', ko: '보통', ja: '中間' },
  mediumDesc:      { en: 'Balanced — all important scenes', he: 'מאוזן — כל הסצנות החשובות', ar: 'متوازن — جميع المشاهد المهمة', fr: 'Équilibré — toutes les scènes importantes', zh: '均衡 — 所有重要场景', pt: 'Equilibrado — todas as cenas importantes', es: 'Equilibrado — todas las escenas importantes', de: 'Ausgewogen — alle wichtigen Szenen', it: 'Bilanciato — tutte le scene importanti', ru: 'Сбалансированный — все важные сцены', ko: '균형 — 모든 중요한 장면', ja: 'バランス — すべての重要なシーン' },
  longLabel:       { en: 'Long', he: 'ארוך', ar: 'طويل', fr: 'Long', zh: '长片', pt: 'Longo', es: 'Largo', de: 'Lang', it: 'Lungo', ru: 'Длинный', ko: '긴', ja: '長い' },
  longDesc:        { en: 'Detailed — every story moment', he: 'מפורט — כל פרט בסיפור', ar: 'مفصل — كل لحظة في القصة', fr: 'Détaillé — chaque moment de l\'histoire', zh: '详细 — 每个故事细节', pt: 'Detalhado — cada momento da história', es: 'Detallado — cada momento de la historia', de: 'Detailliert — jeder Moment der Geschichte', it: 'Dettagliato — ogni momento della storia', ru: 'Подробный — каждый момент истории', ko: '상세 — 모든 이야기 순간', ja: '詳細 — すべてのストーリーモーメント' },

  // ===== STYLE STEP =====
  chooseStyle:     { en: 'Choose your style', he: 'בחר סגנון', ar: 'اختر أسلوبك', fr: 'Choisissez votre style', zh: '选择你的风格', pt: 'Escolha seu estilo', es: 'Elige tu estilo', de: 'Wählen Sie Ihren Stil', it: 'Scegli il tuo stile', ru: 'Выберите стиль', ko: '스타일을 선택하세요', ja: 'スタイルを選択' },
  pickVisual:      { en: 'Pick a visual style and upload character references', he: 'בחר סגנון ויזואלי והעלה דמויות לרפרנס', ar: 'اختر أسلوبًا بصريًا وارفع مراجع الشخصيات', fr: 'Choisissez un style visuel et téléchargez des références', zh: '选择视觉风格并上传角色参考图', pt: 'Escolha um estilo visual e envie referências de personagens', es: 'Elige un estilo visual y sube referencias de personajes', de: 'Wählen Sie einen visuellen Stil und laden Sie Referenzen hoch', it: 'Scegli uno stile visivo e carica i riferimenti', ru: 'Выберите визуальный стиль и загрузите референсы', ko: '비주얼 스타일을 선택하고 캐릭터 레퍼런스를 업로드하세요', ja: 'ビジュアルスタイルを選んでキャラクター参照をアップロード' },
  characterRefs:   { en: 'Character & Atmosphere References', he: 'רפרנס דמויות ואווירה', ar: 'مراجع الشخصيات والأجواء', fr: 'Références personnages et atmosphère', zh: '角色与氛围参考', pt: 'Referências de personagens e atmosfera', es: 'Referencias de personajes y atmósfera', de: 'Charakter- & Atmosphärenreferenzen', it: 'Riferimenti personaggi e atmosfera', ru: 'Референсы персонажей и атмосферы', ko: '캐릭터 & 분위기 레퍼런스', ja: 'キャラクター＆雰囲気リファレンス' },
  upload:          { en: 'Upload', he: 'העלה', ar: 'رفع', fr: 'Télécharger', zh: '上传', pt: 'Enviar', es: 'Subir', de: 'Hochladen', it: 'Carica', ru: 'Загрузить', ko: '업로드', ja: 'アップロード' },

  // ===== LANGUAGE STEP =====
  selectLanguages: { en: 'Select languages', he: 'בחר שפות', ar: 'اختر اللغات', fr: 'Sélectionnez les langues', zh: '选择语言', pt: 'Selecione idiomas', es: 'Selecciona idiomas', de: 'Sprachen auswählen', it: 'Seleziona le lingue', ru: 'Выберите языки', ko: '언어 선택', ja: '言語を選択' },
  chooseLanguages: { en: 'Choose one or more languages for dubbing', he: 'בחר שפה אחת או יותר לדיבוב', ar: 'اختر لغة واحدة أو أكثر للدبلجة', fr: 'Choisissez une ou plusieurs langues de doublage', zh: '选择一种或多种配音语言', pt: 'Escolha um ou mais idiomas para dublagem', es: 'Elige uno o más idiomas para doblaje', de: 'Wählen Sie eine oder mehrere Synchronsprachen', it: 'Scegli una o più lingue per il doppiaggio', ru: 'Выберите один или несколько языков озвучки', ko: '더빙할 언어를 하나 이상 선택하세요', ja: '吹き替え言語を1つ以上選択してください' },

  // ===== TIMELINE =====
  timelineTitle:   { en: 'Timeline', he: 'ציר זמן', ar: 'الجدول الزمني', fr: 'Chronologie', zh: '时间轴', pt: 'Linha do tempo', es: 'Línea de tiempo', de: 'Zeitleiste', it: 'Timeline', ru: 'Таймлайн', ko: '타임라인', ja: 'タイムライン' },
  produceNext:     { en: 'Produce Next', he: 'הפק הבא', ar: 'إنتاج التالي', fr: 'Produire suivant', zh: '制作下一个', pt: 'Produzir próximo', es: 'Producir siguiente', de: 'Nächste produzieren', it: 'Produci successivo', ru: 'Создать следующий', ko: '다음 제작', ja: '次を制作' },
  produceAll:      { en: 'Produce All', he: 'הפק הכל', ar: 'إنتاج الكل', fr: 'Tout produire', zh: '全部制作', pt: 'Produzir tudo', es: 'Producir todo', de: 'Alle produzieren', it: 'Produci tutto', ru: 'Создать все', ko: '전체 제작', ja: 'すべて制作' },
  processing:      { en: 'Processing...', he: 'מעבד...', ar: 'جاري المعالجة...', fr: 'Traitement...', zh: '处理中...', pt: 'Processando...', es: 'Procesando...', de: 'Verarbeitung...', it: 'Elaborazione...', ru: 'Обработка...', ko: '처리 중...', ja: '処理中...' },
  editScene:       { en: 'Edit Scene', he: 'ערוך סצנה', ar: 'تعديل المشهد', fr: 'Modifier la scène', zh: '编辑场景', pt: 'Editar cena', es: 'Editar escena', de: 'Szene bearbeiten', it: 'Modifica scena', ru: 'Редактировать сцену', ko: '장면 편집', ja: 'シーンを編集' },
  sceneTitle:      { en: 'Scene Title', he: 'כותרת סצנה', ar: 'عنوان المشهد', fr: 'Titre de la scène', zh: '场景标题', pt: 'Título da cena', es: 'Título de la escena', de: 'Szenetitel', it: 'Titolo scena', ru: 'Название сцены', ko: '장면 제목', ja: 'シーンタイトル' },
  description:     { en: 'Description', he: 'תיאור', ar: 'الوصف', fr: 'Description', zh: '描述', pt: 'Descrição', es: 'Descripción', de: 'Beschreibung', it: 'Descrizione', ru: 'Описание', ko: '설명', ja: '説明' },
  visualPrompt:    { en: 'Visual prompt for AI...', he: 'הנחיה ויזואלית ל-AI...', ar: 'موجه بصري للذكاء الاصطناعي...', fr: 'Prompt visuel pour l\'IA...', zh: 'AI视觉提示...', pt: 'Prompt visual para IA...', es: 'Prompt visual para IA...', de: 'Visueller Prompt für KI...', it: 'Prompt visivo per l\'IA...', ru: 'Визуальный промпт для ИИ...', ko: 'AI용 시각적 프롬프트...', ja: 'AI用ビジュアルプロンプト...' },
  audioScriptLabel:{ en: 'Audio script (dialogue/narration)', he: 'סקריפט אודיו (דיאלוג/קריינות)', ar: 'نص صوتي (حوار/سرد)', fr: 'Script audio (dialogue/narration)', zh: '音频脚本（对话/旁白）', pt: 'Script de áudio (diálogo/narração)', es: 'Guión de audio (diálogo/narración)', de: 'Audioskript (Dialog/Erzählung)', it: 'Script audio (dialogo/narrazione)', ru: 'Аудиоскрипт (диалог/повествование)', ko: '오디오 스크립트 (대사/내레이션)', ja: 'オーディオスクリプト（セリフ/ナレーション）' },
  done:            { en: 'Done', he: 'סיום', ar: 'تم', fr: 'Terminé', zh: '完成', pt: 'Concluído', es: 'Hecho', de: 'Fertig', it: 'Fatto', ru: 'Готово', ko: '완료', ja: '完了' },
  approved:        { en: 'Approved', he: 'מאושר', ar: 'معتمد', fr: 'Approuvé', zh: '已批准', pt: 'Aprovado', es: 'Aprobado', de: 'Genehmigt', it: 'Approvato', ru: 'Одобрено', ko: '승인됨', ja: '承認済み' },
  producingStatus: { en: 'Producing...', he: 'מייצר...', ar: 'جاري الإنتاج...', fr: 'Production...', zh: '制作中...', pt: 'Produzindo...', es: 'Produciendo...', de: 'Produzieren...', it: 'Producendo...', ru: 'Создание...', ko: '제작 중...', ja: '制作中...' },
  noScenesYet:     { en: 'No scenes yet', he: 'אין סצנות עדיין', ar: 'لا توجد مشاهد بعد', fr: 'Pas encore de scènes', zh: '还没有场景', pt: 'Nenhuma cena ainda', es: 'Sin escenas aún', de: 'Noch keine Szenen', it: 'Nessuna scena ancora', ru: 'Пока нет сцен', ko: '아직 장면이 없습니다', ja: 'まだシーンがありません' },
  generateFirst:   { en: 'Go back to generate a script first', he: 'חזור אחורה כדי ליצור סקריפט', ar: 'ارجع لإنشاء السيناريو أولاً', fr: 'Retournez générer un script d\'abord', zh: '返回先生成剧本', pt: 'Volte para gerar um roteiro primeiro', es: 'Vuelve para generar un guión primero', de: 'Gehen Sie zurück, um zuerst ein Skript zu erstellen', it: 'Torna indietro per generare un copione', ru: 'Вернитесь, чтобы сначала создать сценарий', ko: '먼저 스크립트를 생성하러 돌아가세요', ja: 'まずスクリプトを生成してください' },
  creatingScript:  { en: 'Creating your movie script...', he: 'יוצר את סקריפט הסרט...', ar: 'جاري إنشاء سيناريو الفيلم...', fr: 'Création de votre script...', zh: '正在创建您的电影剧本...', pt: 'Criando seu roteiro...', es: 'Creando tu guión...', de: 'Erstelle Ihr Skript...', it: 'Creazione del copione...', ru: 'Создание вашего сценария...', ko: '영화 대본을 작성하고 있습니다...', ja: '映画スクリプトを作成中...' },
  addManualScene:  { en: 'Add Manual Scene', he: 'הוסף סצנה ידנית', ar: 'إضافة مشهد يدوي', fr: 'Ajouter une scène manuelle', zh: '添加手动场景', pt: 'Adicionar cena manual', es: 'Agregar escena manual', de: 'Manuelle Szene hinzufügen', it: 'Aggiungi scena manuale', ru: 'Добавить сцену вручную', ko: '수동 장면 추가', ja: '手動シーンを追加' },
  approveTip:      { en: 'Review last frame & approve for next scene', he: 'בדוק פריים אחרון ואשר לסצנה הבאה', ar: 'راجع الإطار الأخير ووافق للمشهد التالي', fr: 'Vérifiez la dernière image et approuvez', zh: '审核最后一帧并批准下一场景', pt: 'Revise o último frame e aprove para a próxima cena', es: 'Revisa el último fotograma y aprueba para la siguiente escena', de: 'Letztes Bild prüfen und genehmigen', it: 'Rivedi l\'ultimo fotogramma e approva', ru: 'Просмотрите последний кадр и одобрите', ko: '마지막 프레임을 검토하고 다음 장면을 승인하세요', ja: '最終フレームを確認して次のシーンを承認' },
  approveUnlock:   { en: 'Approve this scene to unlock the next one for production', he: 'אשר סצנה זו כדי לפתוח את הבאה להפקה', ar: 'وافق على هذا المشهد لفتح المشهد التالي للإنتاج', fr: 'Approuvez cette scène pour débloquer la suivante', zh: '批准此场景以解锁下一场景的制作', pt: 'Aprove esta cena para desbloquear a próxima', es: 'Aprueba esta escena para desbloquear la siguiente', de: 'Genehmigen Sie diese Szene, um die nächste freizuschalten', it: 'Approva questa scena per sbloccare la successiva', ru: 'Одобрите эту сцену, чтобы разблокировать следующую', ko: '이 장면을 승인하여 다음 장면을 제작할 수 있게 하세요', ja: 'このシーンを承認して次のシーンを制作可能にする' },
  approve:         { en: 'Approve', he: 'אישור', ar: 'موافقة', fr: 'Approuver', zh: '批准', pt: 'Aprovar', es: 'Aprobar', de: 'Genehmigen', it: 'Approva', ru: 'Одобрить', ko: '승인', ja: '承認' },
  produce:         { en: 'Produce', he: 'הפק', ar: 'إنتاج', fr: 'Produire', zh: '制作', pt: 'Produzir', es: 'Producir', de: 'Produzieren', it: 'Produci', ru: 'Создать', ko: '제작', ja: '制作' },
  retry:           { en: 'Retry', he: 'נסה שוב', ar: 'إعادة المحاولة', fr: 'Réessayer', zh: '重试', pt: 'Tentar novamente', es: 'Reintentar', de: 'Wiederholen', it: 'Riprova', ru: 'Повторить', ko: '재시도', ja: 'リトライ' },
  download:        { en: 'Download', he: 'הורדה', ar: 'تحميل', fr: 'Télécharger', zh: '下载', pt: 'Baixar', es: 'Descargar', de: 'Herunterladen', it: 'Scarica', ru: 'Скачать', ko: '다운로드', ja: 'ダウンロード' },

  // ===== PREVIEW =====
  selectScenePreview: { en: 'Select a scene to preview', he: 'בחר סצנה לתצוגה מקדימה', ar: 'اختر مشهدًا للمعاينة', fr: 'Sélectionnez une scène à prévisualiser', zh: '选择要预览的场景', pt: 'Selecione uma cena para pré-visualizar', es: 'Selecciona una escena para previsualizar', de: 'Wählen Sie eine Szene zur Vorschau', it: 'Seleziona una scena da visualizzare', ru: 'Выберите сцену для просмотра', ko: '미리 볼 장면을 선택하세요', ja: 'プレビューするシーンを選択' },

  // ===== EXPORT =====
  exportMovie:     { en: 'Export Full Movie', he: 'ייצוא סרט מלא', ar: 'تصدير الفيلم الكامل', fr: 'Exporter le film complet', zh: '导出完整影片', pt: 'Exportar filme completo', es: 'Exportar película completa', de: 'Ganzen Film exportieren', it: 'Esporta film completo', ru: 'Экспортировать фильм', ko: '전체 영화 내보내기', ja: '映画全体をエクスポート' },
  audioLanguageLabel: { en: 'Audio Language', he: 'שפת אודיו', ar: 'لغة الصوت', fr: 'Langue audio', zh: '音频语言', pt: 'Idioma do áudio', es: 'Idioma de audio', de: 'Audiosprache', it: 'Lingua audio', ru: 'Язык аудио', ko: '오디오 언어', ja: 'オーディオ言語' },
  startExport:     { en: 'Start Export', he: 'התחל ייצוא', ar: 'بدء التصدير', fr: 'Lancer l\'exportation', zh: '开始导出', pt: 'Iniciar exportação', es: 'Iniciar exportación', de: 'Export starten', it: 'Avvia esportazione', ru: 'Начать экспорт', ko: '내보내기 시작', ja: 'エクスポート開始' },
  exportAgain:     { en: 'Export Again', he: 'ייצוא מחדש', ar: 'تصدير مرة أخرى', fr: 'Exporter à nouveau', zh: '重新导出', pt: 'Exportar novamente', es: 'Exportar de nuevo', de: 'Erneut exportieren', it: 'Esporta di nuovo', ru: 'Экспортировать снова', ko: '다시 내보내기', ja: '再エクスポート' },
  downloadMp4:     { en: 'Download MP4', he: 'הורד MP4', ar: 'تحميل MP4', fr: 'Télécharger MP4', zh: '下载MP4', pt: 'Baixar MP4', es: 'Descargar MP4', de: 'MP4 herunterladen', it: 'Scarica MP4', ru: 'Скачать MP4', ko: 'MP4 다운로드', ja: 'MP4ダウンロード' },
  loadingEngine:   { en: 'Loading video engine...', he: 'טוען מנוע וידאו...', ar: 'جاري تحميل محرك الفيديو...', fr: 'Chargement du moteur vidéo...', zh: '加载视频引擎...', pt: 'Carregando motor de vídeo...', es: 'Cargando motor de video...', de: 'Video-Engine wird geladen...', it: 'Caricamento motore video...', ru: 'Загрузка видеодвижка...', ko: '비디오 엔진 로딩...', ja: 'ビデオエンジン読み込み中...' },
  processingSceneN:{ en: 'Processing scene', he: 'מעבד סצנה', ar: 'معالجة المشهد', fr: 'Traitement de la scène', zh: '处理场景', pt: 'Processando cena', es: 'Procesando escena', de: 'Szene wird verarbeitet', it: 'Elaborazione scena', ru: 'Обработка сцены', ko: '장면 처리 중', ja: 'シーン処理中' },
  mergingScenes:   { en: 'Merging scenes...', he: 'ממזג סצנות...', ar: 'دمج المشاهد...', fr: 'Fusion des scènes...', zh: '合并场景...', pt: 'Mesclando cenas...', es: 'Fusionando escenas...', de: 'Szenen werden zusammengeführt...', it: 'Unione scene...', ru: 'Объединение сцен...', ko: '장면 병합 중...', ja: 'シーン結合中...' },
  preparingDownload:{ en: 'Preparing download...', he: 'מכין הורדה...', ar: 'جاري تحضير التحميل...', fr: 'Préparation du téléchargement...', zh: '准备下载...', pt: 'Preparando download...', es: 'Preparando descarga...', de: 'Download wird vorbereitet...', it: 'Preparazione download...', ru: 'Подготовка скачивания...', ko: '다운로드 준비 중...', ja: 'ダウンロード準備中...' },
  ready:           { en: 'Ready!', he: 'מוכן!', ar: 'جاهز!', fr: 'Prêt !', zh: '准备就绪！', pt: 'Pronto!', es: '¡Listo!', de: 'Fertig!', it: 'Pronto!', ru: 'Готово!', ko: '준비 완료!', ja: '準備完了！' },
  exportFailed:    { en: 'Export failed', he: 'הייצוא נכשל', ar: 'فشل التصدير', fr: 'Exportation échouée', zh: '导出失败', pt: 'Exportação falhou', es: 'Exportación fallida', de: 'Export fehlgeschlagen', it: 'Esportazione fallita', ru: 'Ошибка экспорта', ko: '내보내기 실패', ja: 'エクスポート失敗' },

  // ===== PRICING =====
  choosePlan:      { en: 'Choose your plan', he: 'בחר את התוכנית שלך', ar: 'اختر خطتك', fr: 'Choisissez votre plan', zh: '选择您的计划', pt: 'Escolha seu plano', es: 'Elige tu plan', de: 'Wählen Sie Ihren Plan', it: 'Scegli il tuo piano', ru: 'Выберите тарифный план', ko: '요금제를 선택하세요', ja: 'プランを選択' },
  scaleProduction: { en: 'Scale your movie production with the right tier', he: 'שדרג את הפקת הסרטים שלך עם המסלול הנכון', ar: 'وسّع إنتاج أفلامك مع الفئة المناسبة', fr: 'Développez votre production avec le bon plan', zh: '通过合适的方案扩展您的电影制作', pt: 'Escale sua produção com o plano certo', es: 'Escala tu producción con el nivel adecuado', de: 'Skalieren Sie Ihre Filmproduktion mit dem richtigen Plan', it: 'Scala la tua produzione con il piano giusto', ru: 'Масштабируйте производство фильмов с правильным тарифом', ko: '적합한 요금제로 영화 제작을 확장하세요', ja: '適切なプランで映画制作をスケールアップ' },
  popular:         { en: 'Popular', he: 'פופולרי', ar: 'شائع', fr: 'Populaire', zh: '热门', pt: 'Popular', es: 'Popular', de: 'Beliebt', it: 'Popolare', ru: 'Популярный', ko: '인기', ja: '人気' },
  selectPlan:      { en: 'Select Plan', he: 'בחר תוכנית', ar: 'اختر الخطة', fr: 'Choisir ce plan', zh: '选择计划', pt: 'Selecionar plano', es: 'Seleccionar plan', de: 'Plan auswählen', it: 'Seleziona piano', ru: 'Выбрать план', ko: '요금제 선택', ja: 'プラン選択' },
  perMonth:        { en: '/mo', he: '/חודש', ar: '/شهر', fr: '/mois', zh: '/月', pt: '/mês', es: '/mes', de: '/Monat', it: '/mese', ru: '/мес', ko: '/월', ja: '/月' },
  backToStudio:    { en: 'Back to Studio', he: 'חזרה לסטודיו', ar: 'العودة إلى الاستوديو', fr: 'Retour au studio', zh: '返回工作室', pt: 'Voltar ao estúdio', es: 'Volver al estudio', de: 'Zurück zum Studio', it: 'Torna allo studio', ru: 'Вернуться в студию', ko: '스튜디오로 돌아가기', ja: 'スタジオに戻る' },

  // ===== COMMON =====
  back:            { en: 'Back', he: 'חזרה', ar: 'رجوع', fr: 'Retour', zh: '返回', pt: 'Voltar', es: 'Volver', de: 'Zurück', it: 'Indietro', ru: 'Назад', ko: '뒤로', ja: '戻る' },
  next:            { en: 'Next', he: 'הבא', ar: 'التالي', fr: 'Suivant', zh: '下一步', pt: 'Próximo', es: 'Siguiente', de: 'Weiter', it: 'Avanti', ru: 'Далее', ko: '다음', ja: '次へ' },
  scene:           { en: 'Scene', he: 'סצנה', ar: 'مشهد', fr: 'Scène', zh: '场景', pt: 'Cena', es: 'Escena', de: 'Szene', it: 'Scena', ru: 'Сцена', ko: '장면', ja: 'シーン' },
  delete:          { en: 'Delete', he: 'מחק', ar: 'حذف', fr: 'Supprimer', zh: '删除', pt: 'Excluir', es: 'Eliminar', de: 'Löschen', it: 'Elimina', ru: 'Удалить', ko: '삭제', ja: '削除' },

  // ===== ERROR MESSAGES =====
  freePlanLimit:   { en: 'Free plan allows 2 demo scenes. Upgrade for unlimited production!', he: 'תוכנית חינמית מאפשרת 2 סצנות דמו. שדרג להפקה ללא הגבלה!', ar: 'تتيح الخطة المجانية مشهدين تجريبيين. قم بالترقية لإنتاج غير محدود!', fr: 'Le plan gratuit permet 2 scènes démo. Mettez à niveau pour une production illimitée !', zh: '免费计划允许2个演示场景。升级以获得无限制制作！', pt: 'O plano gratuito permite 2 cenas demo. Atualize para produção ilimitada!', es: 'El plan gratuito permite 2 escenas demo. ¡Actualiza para producción ilimitada!', de: 'Der kostenlose Plan erlaubt 2 Demo-Szenen. Upgraden für unbegrenzte Produktion!', it: 'Il piano gratuito consente 2 scene demo. Aggiorna per produzione illimitata!', ru: 'Бесплатный план позволяет 2 демо-сцены. Обновитесь для безлимитного производства!', ko: '무료 플랜은 2개의 데모 장면을 허용합니다. 무제한 제작을 위해 업그레이드하세요!', ja: '無料プランではデモシーン2つまでです。無制限制作にはアップグレードを！' },
  quotaExceeded:   { en: 'Quota exceeded. Please wait or check your billing plan.', he: 'מכסה אזלה. המתן או בדוק את תוכנית החיוב.', ar: 'تم تجاوز الحصة. يرجى الانتظار أو التحقق من خطة الفوترة.', fr: 'Quota dépassé. Veuillez patienter ou vérifier votre plan de facturation.', zh: '配额已超出。请稍等或检查您的计费计划。', pt: 'Cota excedida. Aguarde ou verifique seu plano de faturamento.', es: 'Cuota excedida. Espera o verifica tu plan de facturación.', de: 'Kontingent überschritten. Bitte warten oder Abrechnungsplan prüfen.', it: 'Quota superata. Attendere o verificare il piano di fatturazione.', ru: 'Квота исчерпана. Подождите или проверьте план оплаты.', ko: '할당량이 초과되었습니다. 잠시 기다리거나 결제 플랜을 확인하세요.', ja: 'クォータ超過。しばらく待つか、請求プランを確認してください。' },

  // ===== UI LANGUAGE SELECTOR =====
  uiLanguage:      { en: 'Interface Language', he: 'שפת ממשק', ar: 'لغة الواجهة', fr: 'Langue de l\'interface', zh: '界面语言', pt: 'Idioma da interface', es: 'Idioma de la interfaz', de: 'Oberflächensprache', it: 'Lingua interfaccia', ru: 'Язык интерфейса', ko: '인터페이스 언어', ja: 'インターフェース言語' },

  // ===== ADDITIONAL STRINGS =====
  storySubtitle:   { en: 'Paste a book excerpt, script, or describe your movie idea', he: 'הדבק קטע מספר, תסריט, או תאר את רעיון הסרט שלך', ar: 'الصق مقتطفًا من كتاب أو سيناريو أو صف فكرة فيلمك', fr: 'Collez un extrait de livre, un script ou décrivez votre idée de film', zh: '粘贴书籍摘录、剧本，或描述您的电影创意', pt: 'Cole um trecho de livro, roteiro ou descreva sua ideia de filme', es: 'Pega un extracto de libro, guión o describe tu idea de película', de: 'Fügen Sie einen Buchauszug, ein Skript ein oder beschreiben Sie Ihre Filmidee', it: 'Incolla un estratto di libro, copione o descrivi la tua idea per il film', ru: 'Вставьте отрывок из книги, сценарий или опишите идею фильма', ko: '책 발췌, 대본을 붙여넣거나 영화 아이디어를 설명하세요', ja: '書籍の抜粋や台本を貼り付けるか、映画のアイデアを説明してください' },
  creativeOption:  { en: '✨ Creative — AI enriches with cinematic depth', he: '✨ יצירתי — AI מעשיר בעומק קולנועי', ar: '✨ إبداعي — الذكاء الاصطناعي يثري بعمق سينمائي', fr: '✨ Créatif — L\'IA enrichit de profondeur cinématique', zh: '✨ 创意 — AI增添电影深度', pt: '✨ Criativo — IA enriquece com profundidade cinematográfica', es: '✨ Creativo — IA enriquece con profundidad cinematográfica', de: '✨ Kreativ — KI bereichert mit filmischer Tiefe', it: '✨ Creativo — L\'IA arricchisce con profondità cinematografica', ru: '✨ Творческий — ИИ обогащает кинематографической глубиной', ko: '✨ 크리에이티브 — AI가 영화적 깊이를 더합니다', ja: '✨ クリエイティブ — AIが映画的な深みを加えます' },
  strictOption:    { en: '📐 Strict — follows your text word for word', he: '📐 מדויק — עוקב אחרי הטקסט מילה במילה', ar: '📐 دقيق — يتبع النص كلمة بكلمة', fr: '📐 Strict — suit votre texte mot à mot', zh: '📐 严格 — 逐字遵循您的文本', pt: '📐 Estrito — segue seu texto palavra por palavra', es: '📐 Estricto — sigue tu texto palabra por palabra', de: '📐 Strikt — folgt Ihrem Text wortgetreu', it: '📐 Rigoroso — segue il testo parola per parola', ru: '📐 Точный — следует тексту дословно', ko: '📐 엄격 — 텍스트를 그대로 따릅니다', ja: '📐 厳密 — テキストに忠実に従います' },
  aiOption:        { en: '🤖 AI — describe an idea, AI builds the script', he: '🤖 AI — תאר רעיון, ה-AI בונה את הסקריפט', ar: '🤖 ذكاء اصطناعي — صف فكرة، الذكاء الاصطناعي يبني السيناريو', fr: '🤖 IA — décrivez une idée, l\'IA construit le script', zh: '🤖 AI — 描述创意，AI构建剧本', pt: '🤖 IA — descreva uma ideia, a IA constrói o roteiro', es: '🤖 IA — describe una idea, la IA construye el guión', de: '🤖 KI — beschreiben Sie eine Idee, KI erstellt das Skript', it: '🤖 IA — descrivi un\'idea, l\'IA costruisce il copione', ru: '🤖 ИИ — опишите идею, ИИ создаст сценарий', ko: '🤖 AI — 아이디어를 설명하면 AI가 대본을 만듭니다', ja: '🤖 AI — アイデアを説明すると、AIがスクリプトを作成します' },
  manualOption:    { en: '📖 Text — paste a book/script, AI splits to scenes', he: '📖 טקסט — הדבק ספר/תסריט, AI מפצל לסצנות', ar: '📖 نص — الصق كتابًا/سيناريو، الذكاء الاصطناعي يقسم إلى مشاهد', fr: '📖 Texte — collez un livre/script, l\'IA découpe en scènes', zh: '📖 文本 — 粘贴书籍/剧本，AI分割成场景', pt: '📖 Texto — cole um livro/roteiro, IA divide em cenas', es: '📖 Texto — pega un libro/guión, IA divide en escenas', de: '📖 Text — fügen Sie ein Buch/Skript ein, KI teilt in Szenen', it: '📖 Testo — incolla un libro/copione, l\'IA divide in scene', ru: '📖 Текст — вставьте книгу/сценарий, ИИ разделит на сцены', ko: '📖 텍스트 — 책/대본을 붙여넣으면 AI가 장면으로 분할합니다', ja: '📖 テキスト — 本/台本を貼り付け、AIがシーンに分割します' },
  apiKeyHelp:      { en: 'Enter your Google AI Studio API key. The key is saved locally in your browser.', he: 'הכנס את מפתח ה-API של Google AI Studio. המפתח נשמר מקומית בדפדפן שלך.', ar: 'أدخل مفتاح API الخاص بـ Google AI Studio. يُحفظ المفتاح محليًا في متصفحك.', fr: 'Entrez votre clé API Google AI Studio. La clé est sauvegardée localement dans votre navigateur.', zh: '输入您的Google AI Studio API密钥。密钥保存在您的浏览器本地。', pt: 'Insira sua chave API do Google AI Studio. A chave é salva localmente no seu navegador.', es: 'Ingresa tu clave API de Google AI Studio. La clave se guarda localmente en tu navegador.', de: 'Geben Sie Ihren Google AI Studio API-Schlüssel ein. Der Schlüssel wird lokal in Ihrem Browser gespeichert.', it: 'Inserisci la tua chiave API di Google AI Studio. La chiave viene salvata localmente nel tuo browser.', ru: 'Введите ваш API-ключ Google AI Studio. Ключ сохраняется локально в вашем браузере.', ko: 'Google AI Studio API 키를 입력하세요. 키는 브라우저에 로컬로 저장됩니다.', ja: 'Google AI Studio APIキーを入力してください。キーはブラウザにローカル保存されます。' },
  producingScenes: { en: 'Producing scenes...', he: 'מייצר סצנות...', ar: 'جاري إنتاج المشاهد...', fr: 'Production des scènes...', zh: '正在制作场景...', pt: 'Produzindo cenas...', es: 'Produciendo escenas...', de: 'Szenen werden produziert...', it: 'Produzione scene...', ru: 'Создание сцен...', ko: '장면 제작 중...', ja: 'シーン制作中...' },
  rendering:       { en: 'Rendering...', he: 'מרנדר...', ar: 'جاري العرض...', fr: 'Rendu...', zh: '渲染中...', pt: 'Renderizando...', es: 'Renderizando...', de: 'Rendern...', it: 'Rendering...', ru: 'Рендеринг...', ko: '렌더링 중...', ja: 'レンダリング中...' },
  exportMovieBtn:  { en: 'Export Movie 🎬', he: 'ייצוא סרט 🎬', ar: 'تصدير الفيلم 🎬', fr: 'Exporter le film 🎬', zh: '导出影片 🎬', pt: 'Exportar filme 🎬', es: 'Exportar película 🎬', de: 'Film exportieren 🎬', it: 'Esporta film 🎬', ru: 'Экспорт фильма 🎬', ko: '영화 내보내기 🎬', ja: '映画エクスポート 🎬' },
  exportSuccess:   { en: 'Movie exported successfully!', he: 'הסרט יוצא בהצלחה!', ar: 'تم تصدير الفيلم بنجاح!', fr: 'Film exporté avec succès !', zh: '电影导出成功！', pt: 'Filme exportado com sucesso!', es: '¡Película exportada con éxito!', de: 'Film erfolgreich exportiert!', it: 'Film esportato con successo!', ru: 'Фильм успешно экспортирован!', ko: '영화 내보내기 완료!', ja: '映画のエクスポートが成功しました！' },
};

// Helper: get translated string
export function t(key: string, lang: UILanguage): string {
  const entry = translations[key];
  if (!entry) return key; // fallback to key name
  return entry[lang] || entry.en || key; // fallback to English, then key
}

// Helper: check if language is RTL
export function isRTL(lang: UILanguage): boolean {
  return lang === 'he' || lang === 'ar';
}
